### ISSUE TITLE
feat: Protocol Buffers Support (protobuf)

### ISSUE THREAD

**Issue by nosmirck** [VeryGoodOpenSource/dart_frog#101]
**Description**

[Protocol Buffers](https://developers.google.com/protocol-buffers/) or "[protobuf](https://github.com/google/protobuf.dart)" is a tool (developed by Google) to provide mechanisms to serialize structured data in a very efficient way making the data transferred very small and the serialization blazing fast!.

**Proposal**

It would be great if dart_frog supported protobuf or at least leave a clear way to be handled by a plugin or brick.

**Requirements**

- [ ] Response Models for the endpoints to be automatically generated based on .proto files.
- [ ] Generated Models can be bundled in a shared package between the server and the client applications.

**Additional Context**

[Dart is supported!](https://developers.google.com/protocol-buffers/docs/darttutorial)

**Comment by mtwichel** [comment]
@felangel Now that we have expanded examples, would it be okay if I merged in my protobuf example and made it a tutorial? I would also make sure it has test coverage and all that jazz.

**Comment by felangel** [comment]
As discussed, closing this issue since the answer provided by @mtwichel is quite thorough and illustrates the steps needed to use protobuf in the context of a Dart Frog application.
