### ISSUE TITLE
fix: firebase database and dart_frog api fetch error

### ISSUE THREAD

**Issue by dhrubrawat66** [VeryGoodOpenSource/dart_frog#1030]
**Description**
i created the project by using firebase database and dart_frog,
when i try to fetch the data by using following command
$ curl --request GET --url http://127.0.0.1:8080/db/fbase
in first attempt it throw result as i wish
but in second second attempt throw error as below
  - Internal Server Error
darrt frog terminal throw given error
![Screenshot 2023-09-12 205020](https://github.com/VeryGoodOpenSource/dart_frog/assets/85351405/e9f6b862-9172-456e-866f-13198fcc77ca)

Note:-
 - os window 11
 - same eror occured when i tried create the api by using mongodb database.

**Comment by alestiago** [comment]
Hi @dhrubrawat66 ! For opening an issue 🙌 

I believe this is not precisely an issue in Dart Frog but an issue on how you are initialising Firebase in Dart Frog. I recommend to move the initialising code (which is only meant to run once) to Dart Frog's init method, you can check the documentation [here](https://dartfrog.vgv.dev/docs/advanced/custom_init_method).

**Comment by alestiago** [comment]
Hi @dhrubrawat66, I'm closing this issue since there hasn't been a reply in a while. I hope my previous comment helped you out. If it didn't let me know and we can re-open the issue! Thank you 🙌
