### ISSUE TITLE
fix:  No active package dart_frog_cli after activation

### ISSUE THREAD

**Issue by Michael-Lyon** [VeryGoodOpenSource/dart_frog#1100]
**No active package dart_frog_cli**

After using the "sudo dart pub global activate dart_frog_cli" to activate the package.
I am unable to access it as it says "No active package dart_frog_cli"

I am using a MacBook Pro 2020 m1 

**Steps To Reproduce**

1. Go to 'sudo dart pub global activate dart_frog_cli'
2. dart_frog dev
3. No active package dart_frog_cli.

**Comment by Michael-Lyon** [comment]
when I run dart pub global list I can see the package

**Comment by tomarra** [comment]
Hi @Michael-Lyon 👋 

We typically don't troubleshoot environment issues unless it is a pervasive issue that many people can replicate and report steps on how to do so. I suggest making sure that you are able to activate other packages via `dart pub activate` to ensure your environment is setup and working correctly.

Closing as won't fix.
