### ISSUE TITLE
fix: Flutter web CORS request handling

### ISSUE THREAD

**Issue by vimptech-git** [VeryGoodOpenSource/dart_frog#1137]
**Description**

Please share code for dart frog CORS request handle when use flutter web development/production

**Comment by felangel** [comment]
Hey 👋
Check out https://dartfrog.vgv.dev/docs/advanced/cors

**Comment by alestiago** [comment]
Hey @vimptech-git  since this seems to be silent for a while, I am closing this for now. If anything comes up, don't hesitate on telling.
