### ISSUE TITLE
How can we use frog as a android application also server run in background

### ISSUE THREAD

**Issue by vimptech-git** [VeryGoodOpenSource/dart_frog#1148]
Use frog http server as a android app with backend (sqlitedb)

**Comment by tomarra** [comment]
Hi @vimptech-git 👋 thanks for raising this issue.

As of now the Dart Frog framework is really meant for deployment to a backend server on a cloud service. This is shown in our [docs as well](https://github.com/VeryGoodOpenSource/dart_frog/tree/main/docs/docs/deploy) as they are focused on services like [Google Cloud Run](https://github.com/VeryGoodOpenSource/dart_frog/blob/main/docs/docs/deploy/google-cloud-run.md) or [AWS App Runner](https://github.com/VeryGoodOpenSource/dart_frog/blob/main/docs/docs/deploy/aws-app-runner.md). While you may be able to get this running locally in a mobile application it's not a use case that we're looking to pursue or support at this time.

Closing as "Won't Fix".
