### ISSUE TITLE
fix:  need clarity around static files

### ISSUE THREAD

**Issue by djkingCanada** [VeryGoodOpenSource/dart_frog#1150]
Static files documentation says:
- note In production, only files that are in the /public directory at build time will be served.

It would be helpful if there was an explanation as to why that is. - do the files get compiled into the binary - if not why the restriction on static files?  I'm doing a docker build and the system isn't finding the files in public - so I'm trying to track down what's going on, but it's not obvious from the docs if the files are part of the binary or need to be added to the docker image separately.

**Comment by wolfenrain** [comment]
Hi! The reason static files are under `public/` is simply because that is how we made it. Are you trying to build a PROD dart frog docker build using our provide build commands?

If so it might be that the docker file does not add the `public/` files to the docker image result, which would be a bug on our side.

**Comment by djkingCanada** [comment]
@wolfenrain yeah that wasn't the question.  The question was: are file in public at build time part of the bin, much like assets in a flutter app [and that would explain the documentation that says only files in public at build time will be served] or do the files need to shipped separately.  If the files are not part of the bin (and and this point I don't think they are) why the comment in the documentation saying only files that are in public at build time will be served?

**Comment by starlabman** [comment]
## Static Files Handling

In a production environment, only files that reside in the `/public` directory at build time will be served by the system. This document aims to clarify the rationale behind this restriction and provide guidance on how to manage static files effectively.

### Build Time Behavior

During the build process, only files located in the `/public` directory are considered for serving in the production environment. This decision is based on the need to streamline the deployment process and optimize performance.

#### Compilation and Docker Image Inclusion

The static files in the `/public` directory undergo a process of bundling and optimization during the build, ensuring efficient delivery to clients. However, they are not directly compiled into the binary. Instead, they remain as separate files within the `/public` directory.

If you are using Docker to deploy your application, you need to include these static files in the Docker image separately. This separation allows for flexibility and ease of updating static assets without rebuilding the entire application.

### Docker Build Instructions

If your system requires static files to be included in the Docker image separately, you can use the following Dockerfile snippet as a guide:

```dockerfile
# Example Dockerfile snippet to include static files
FROM [base image]

# Copy the /public directory into the Docker image
COPY ./public /app/public

# Additional Dockerfile steps...

**Comment by phatwillis** [comment]
People often wonder why only files in the /public folder are shown. Here's the deal: during building, files in /public are grouped together but not mixed into the main program. This makes it easier to tweak things without redoing everything. If you're using Docker, make sure to pack /public files into the picture separately. If things aren't working, double-check that you've included the /public folder when building with Docker.

**Comment by akash4566** [comment]
# Use an official runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies
RUN npm install

# Copy static files into the container
COPY ./public ./public

# Copy the rest of the application code
COPY . .

# Specify the port the app runs on
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]

**Comment by djkingCanada** [comment]
Thanks for the feed back.  I still think the docs that say: "In a production environment, only files that reside in the /public directory at build time will be served by the system."  Is misleading.  If that was true then a copying files into docker wouldn't work.

**Comment by tomarra** [comment]
Hi all 👋 

It seems from the conversation here that this is actually a docker config issue rather then something we would be fixing within Dart Frog itself. Overall we do have documentation around [serving static files](https://dartfrog.vgv.dev/docs/basics/serving-static-files) and examples for a [custom dockerfile](https://dartfrog.vgv.dev/docs/advanced/custom_dockerfile) which actually does call out the `/public` path in it.

Given that, I'm closing this as a won't fix.
