### ISSUE TITLE
max number of websockets 

### ISSUE THREAD

**Issue by develocode777** [VeryGoodOpenSource/dart_frog#1172]
**Description**

Hello, is there a limit of number of websockets that can be opened besides hardware limitations? I try to open many connections and every time it stops at 10749 connections, I think that is a bit low.

**Steps To Reproduce**

server code:

```
import 'package:dart_frog/dart_frog.dart';
import 'package:dart_frog_web_socket/dart_frog_web_socket.dart';

int count = 0;
Handler get onRequest {
  return webSocketHandler((channel, protocol) {
    print(++count);
    channel.stream.listen((message) {
      print(message);
    });
    channel.sink.add('hi');
  });
}
```

flutter code:

```
import 'package:flutter/material.dart';
import 'package:web_socket_channel/web_socket_channel.dart';
import 'package:web_socket_channel/status.dart' as status;
import 'package:web_socket_client/web_socket_client.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatefulWidget {
  const MainApp({super.key});

  @override
  State<MainApp> createState() => _MainAppState();
}

class _MainAppState extends State<MainApp> {
  connect() async {
    for (int i = 1; i <= 12000; ++i) {
      final socket = WebSocket(Uri.parse('ws://localhost:8080/ws'));
      socket.messages.listen((message) {
        print(message);
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              ElevatedButton(onPressed: connect, child: Text('connect')),
            ],
          ),
        ),
      ),
    );
  }
}

```

**Additional Context**

I use a M1 macbook with 16 GB of memory.

**Comment by renancaraujo** [comment]
This is an interesting question and I am also curious about the limits here. Some stuff to consider:
- System constraints go from OS configurations (ex: max open files) to hardware resources (ex: RAM memory) 
- Don't use the dev server (`dart_frog dev`) as a performance metric.

I am curious what error you see when that apparent limit is reached.

**Comment by develocode777** [comment]
I repeated the test with a dart app (not flutter) and it only opens the exact same number but now i have an error message "SocketException (SocketException: Connection failed (OS Error: Too many open files, errno = 24)", so its an OS issue.

**Comment by develocode777** [comment]
I managed to fix the error by editing /etc/security/limits.conf and running ulimit -n 1000000 (this time on a linux machine) and it went up to 20k websockets, but beyond this limit I understand that you need to set up more ip addresses.
