### ISSUE TITLE
fix: Concurrency Issues

### ISSUE THREAD

**Issue by vimptech-git** [VeryGoodOpenSource/dart_frog#1181]
**Description**
"When I use sleep(Duration(seconds: 25)) in one route, afterward, I run another route, it shows loading and executes after the pending route is completed."

**Comment by tomarra** [comment]
Hi @vimptech-git 👋 Thanks for opening an issue. Would you be able to submit a code example that illustrates this behavior so we can attempt to reproduce locally and accurately triage this ticket? Thanks in advance!

**Comment by tomarra** [comment]
Closing this out given no further information given. 

@vimptech-git if you do have more information to provide here then please feel free to post and we can re-open to investigate.
