### ISSUE TITLE
docs: Add Globe to Deployment section in Docs

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/dart_frog#1192]
**Description**

With the launch of Globe it looks like they have a section in their documentation on Dart Frog deployment, https://docs.globe.dev/frameworks/dart-frog. Let's add this to our deployment docs as well.

**Requirements**

- [ ] We have tested deployment of a sample Dart Frog server/project on Globe
- [ ] The deployment steps are documented in the Dart Frog docs

**Comment by alestiago** [comment]
I've moved this to "In Progress". I'm planning to have a read through the entire Globe documentation and try the tool out.
