### ISSUE TITLE
How to inject variables into context in a certain route

### ISSUE THREAD

**Issue by ZhongGuanbin** [VeryGoodOpenSource/dart_frog#1209]
For example, the route on my login interface is sign/in, and I have obtained the user's permission, userPermission. I want to inject userPermission into the context so that other routes can also access it. How can I implement this？Thanks everyone! God Bless you!

**Comment by alestiago** [comment]
Hi @ZhongGuanbin ! Thanks for submitting an issue. I think the solution you're looking for might be in the [Dart Frog documentation about Dependeny Injection using a Provider](https://dartfrog.vgv.dev/docs/basics/dependency-injection#provider).

Let me know if this helps 💙

**Comment by ZhongGuanbin** [comment]
> Hi @ZhongGuanbin ! Thanks for submitting an issue. I think the solution you're looking for might be in the [Dart Frog documentation about Dependeny Injection using a Provider](https://dartfrog.vgv.dev/docs/basics/dependency-injection#provider).
> 
> Let me know if this helps 💙


Hi @alestiago ! Thank you very much for your reply! I now forward requests to the root route through internal forwarding and implement dependency injection in the middleware of the root route. I feel that my usage is still a bit problematic because provider creates the provided value only when it is accessed, so I must use context. read<T>() in the routing of the root context. I have an idea now to create Middleware in the routing, but due to other more urgent tasks, I have not yet verified it. I have just been exposed to network programming, so my ideas may be a bit absurd. I will update this issue after verification. Thank you again for your reply!

**Comment by alestiago** [comment]
I'm glad it helped. I am closing this for now. If anything comes up, don't hesitate on telling! 💙

**Comment by ZhongGuanbin** [comment]
来信获悉，感谢您的支持！耑此奉复                                                                           钟冠彬This is an automatic reply, confirming that your e-mail was received.Thank you
