### ISSUE TITLE
fix: Error parsing request

### ISSUE THREAD

**Issue by enzo-desimone** [VeryGoodOpenSource/dart_frog#1260]
**Description**

in the console of the container where the dart frog backend is running, some errors appear, which, not after careful analysis, do not seem to depend on the implementation made.

```
Error parsing request.
Invalid argument (requestedUri): handlerPath "/" and url "43" must combine to equal requestedUri path "443".: Instance of '_SimpleUri'
dart:isolate  _RawReceivePort._handleMessage
```

```
Error parsing request.
FormatException: Invalid port (at character 9)
http://:::8080/
        ^
dart:isolate  _RawReceivePort._handleMessage
```

**Comment by alestiago** [comment]
Hi @enzo-desimone 👋 ! Can you provide minimal reproductive steps?

**Comment by alestiago** [comment]
Hey @enzo-desimone since this seems to be silent for a while, I am closing this for now. If anything comes up, don't hesitate on telling.
