### ISSUE TITLE
fix: zsh: command not found: dart_frog

### ISSUE THREAD

**Issue by NBPTruong** [VeryGoodOpenSource/dart_frog#1263]
after I write this line "dart pub global activate dart_frog_cli" it shows the following warning line "Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

   export PATH="$PATH":"$HOME/.pub-cache/bin""
and when I write the command line "dart_frog create my_project"
then it says "zsh: command not found: dart_frog"
Please guide me to fix it.
Thanks a lot.
<img width="566" alt="image" src="https://github.com/VeryGoodOpenSource/dart_frog/assets/153047976/ac0ad404-fd8d-479d-b63f-977fd44050a9">

**Comment by alestiago** [comment]
Hi @NBPTruong 👋 !

I believe this is not a Dart Frog related issue, but instead a problem you're experiencing because you have not added `$HOME/.pub-cache/bin` to your path.

Assuming you're using the  Z shell (zsh) resolve simply open  your file `~/.zshrc ` and adding:
```env
export PATH="$PATH":"$HOME/.pub-cache/bin"
```

Let me know if this helps 💙 🙌 !

**Comment by NBPTruong** [comment]
I still get the same error
<img width="1149" alt="image" src="https://github.com/VeryGoodOpenSource/dart_frog/assets/153047976/420d96e9-ba41-45cd-9e74-f6549fedcf64">

**Comment by wamynobe** [comment]
After adding Path, you should run `source ~/.zshrc`

**Comment by tomarra** [comment]
Hi @NBPTruong, seems like this is a local setup issue and not something that would be a code change or fix in Dart Frog. Given that I'm closing this out as "won't fix"
