### ISSUE TITLE
chore: Release for Dart Frog CLI and Package

### ISSUE THREAD

**Issue by tomarra** [VeryGoodOpenSource/dart_frog#1274]
**Description**

Need to make releases for Dart Frog CLI and Package given the latest changes.

**Requirements**

- [ ] No functional changes to the code
- [ ] Dart Frog CLI v1.2.2 is released
- [ ] Dart Frog v1.1.0 is released

**Comment by alestiago** [comment]
Closing, since [Dart Frog 1.1.0](https://github.com/VeryGoodOpenSource/dart_frog/releases/tag/dart_frog-v1.1.0) and [Dart Frog CLI 1.1.2](https://github.com/VeryGoodOpenSource/dart_frog/releases/tag/dart_frog_cli-v1.2.2) have been released.
