### ISSUE TITLE
fix: Dockerfile build fails

### ISSUE THREAD

**Issue by aa7831** [VeryGoodOpenSource/dart_frog#129]
**Description**

Deploying the project on Heroku via Dockerfile (produced by dart_frog build) reports an error: 

<img width="735" alt="Screenshot 2022-07-01 at 4 23 00 PM" src="https://user-images.githubusercontent.com/90097437/176893593-279310cf-743c-4c4e-adff-a04865a1801b.png">

I have also tried using the Dockerfile on my local Docker and the build fails with the same error. 

**Steps To Reproduce**

1. build your dart frog project
2. try deploying via dockerfile

**Temporary fix**
Removing the following lines from the Dockerfile fixed the error:
FROM scratch
COPY --from=build /runtime/ /
COPY --from=build /app/bin/server /app/bin/

**Comment by felangel** [comment]
@aa7831 can you please provide the exact steps you took to reproduce the error? Thanks!

**Comment by aa7831** [comment]
1. Create a project (let's say the default project created by dart_frog create)
2. Build the project using dart_frog build
3. Navigate to the build folder with the Dockerfile

**Deploying Locally**
1. Build an image (docker build . -t <name>)
2. Run the image
3. Error occurs:
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown

**Deploying on Heroku**
1. Create an heroku app, set stack to container
2. Add heroku.yml to build directory:
<img width="246" alt="Screenshot 2022-07-06 at 11 12 35 AM" src="https://user-images.githubusercontent.com/90097437/177491295-c589715e-0815-4682-b764-76819607a414.png">


4. Deploy the app on heroku:
5. heroku container:push web
6. heroku container:release web
7. heroku logs --tail 
8. Error occurs:

<img width="698" alt="Screenshot 2022-07-06 at 11 17 15 AM" src="https://user-images.githubusercontent.com/90097437/177492167-509f4de7-913a-4296-b181-bbd8e090f733.png">

**Comment by felangel** [comment]
@aa7831 I am unable to reproduce can you confirm you're running the exact same steps:

1. `dart pub global activate dart_frog_cli`
2. `dart_frog create my_server`
3. `cd my_server`
4. `dart_frog build`
5. cd `build`
6. `docker build .`
7. `docker run -d -p 8080:8080 --rm <image>`

When running the above steps I am able to successfully build and run the docker image:

```
$ docker build .
[+] Building 8.8s (14/14) FINISHED                                              
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 760B                                       0.0s
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 126B                                          0.0s
 => [internal] load metadata for docker.io/library/dart:stable             0.3s
 => [build 1/7] FROM docker.io/library/dart:stable@sha256:53332996ddcdd1f  0.0s
 => [internal] load build context                                          0.1s
 => => transferring context: 11.73kB                                       0.1s
 => CACHED [build 2/7] WORKDIR /app                                        0.0s
 => [build 3/7] COPY pubspec.* ./                                          0.0s
 => [build 4/7] RUN dart pub get                                           2.9s
 => [build 5/7] COPY . .                                                   0.0s
 => [build 6/7] RUN dart pub get --offline                                 0.6s
 => [build 7/7] RUN dart compile exe bin/server.dart -o bin/server         4.6s 
 => CACHED [stage-1 1/2] COPY --from=build /runtime/ /                     0.0s 
 => [stage-1 2/2] COPY --from=build /app/bin/server /app/bin/              0.0s 
 => exporting to image                                                     0.0s 
 => => exporting layers                                                    0.0s
 => => writing image sha256:a5410c9674a646098f3c27920cbc2055f0b1f8a3fefeb  0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them

Desktop/my_server/build is 📦 v1.0.0+1 via 🎯 v2.17.5 
$ docker run -d -p 8080:8080 --rm sha256:a5410c9674a646098f3c27920cbc2055f0b1f8a3fefeb
aa6c9c1908ec7444c4f04aaf38e42aa391b41547da56b22c9c3dce0e811e4ef3
```

If the above steps don't work for you can you please provide some more information regarding the operating system you're running on and potentially a screen recording of the above steps? Thanks and sorry for the inconvenience!

**Comment by wolfenrain** [comment]
I am not able to reproduce it here either. The docker image that is built is fully run-able without any missing files.

**Comment by aa7831** [comment]
Hi, the docker file is working fine in my local environment now. I suppose it's an issue with my method of deploying to heroku.

Thanks!

**Comment by ekokurniadi** [comment]
@aa7831 are you already have some solution for this issue ?
