### ISSUE TITLE
fix: ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 57735, uri=http://127.0.0.1:57715/status

### ISSUE THREAD

**Issue by rifay-next99** [VeryGoodOpenSource/dart_frog#1298]
When i use the prisma orm in dart_frog. the tables are created successfully in local . but the get and adding the data in. tale the error shows like this

ERROR - 2024-02-21 21:31:51.058956
GET /signIn
Error thrown by handler.
ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = 127.0.0.1, port = 57735, uri=http://127.0.0.1:57715/status

**Comment by tomarra** [comment]
Hi @rifay-next99 👋 thanks for opening this issue.

With no reproduction steps or sample project I don't think we can triage this. If your still having this issue and can supply steps or even better a sample project that we can just open and run to see the issue we can reopen this for triage. Until then closing this as "won't fix".
