### ISSUE TITLE
feat: option to disable watcher wher runnig "dart_frog dev"

### ISSUE THREAD

**Issue by Damianoux** [VeryGoodOpenSource/dart_frog#1307]
I'd like to use FreeBSD for development.
I am able to run "dart_frog build"  but not "dart frog dev", because inotify api is missing, i got the error:
FileSystemException: Failed to initialize file system entity watcher, path = '/dart_frog/myproject' (OS Error: Function not implemented, errno = 38)
Could it be possible to prevent watcher to run when executing "dart pub dev" with a command line option?

**Comment by tomarra** [comment]
Hi @Damianoux 👋 Thanks for opening this issue.

When running the `dev` command we want to always include the watcher as it's running in a dev mode.
