### ISSUE TITLE
[process] Server process has been terminated，The error has been consistently reported in VSCode.

### ISSUE THREAD

**Issue by Chenlin2020-center** [VeryGoodOpenSource/dart_frog#1312]
✓ Running on http://localhost:8080 (0.2s)
The Dart VM service is listening on http://127.0.0.1:8181/IDGi_8oYxNc=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/IDGi_8oYxNc=/devtools?uri=ws://127.0.0.1:8181/IDGi_8oYxNc=/ws
[hotreload] Hot reload is enabled.
Press either R or r to reload
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = ::, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032:7)
<asynchronous suspension>
#1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1812:15)
<asynchronous suspension>
#2      _ServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2097:15)
<asynchronous suspension>
#3      _HttpServer.bind.<anonymous closure> (dart:_http/http_impl.dart:3186:27)
<asynchronous suspension>
#4      serve (package:shelf/shelf_io.dart:60:16)
<asynchronous suspension>
#5      withHotreload.<anonymous closure> (package:shelf_hotreload/src/with_hotreload.dart:81:21)
<asynchronous suspension>
#6      withHotreload (package:shelf_hotreload/src/with_hotreload.dart:102:3)
<asynchronous suspension>
[process] Server process has been terminated
StdinException: Error setting terminal line mode, OS Error: 句柄无效。
, errno = 6
PS D:\DartProj\my_project> dart_frog dev
✓ Running on http://localhost:8080 (0.2s)
The Dart VM service is listening on http://127.0.0.1:8181/F3K2U8HRi0Q=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/F3K2U8HRi0Q=/devtools?uri=ws://127.0.0.1:8181/F3K2U8HRi0Q=/ws
[hotreload] Hot reload is enabled.
Press either R or r to reload
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = ::, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032:7)
<asynchronous suspension>
#1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1812:15)
<asynchronous suspension>
#2      _ServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2097:15)
<asynchronous suspension>
#3      _HttpServer.bind.<anonymous closure> (dart:_http/http_impl.dart:3186:27)
<asynchronous suspension>
#4      serve (package:shelf/shelf_io.dart:60:16)
<asynchronous suspension>
#5      withHotreload.<anonymous closure> (package:shelf_hotreload/src/with_hotreload.dart:81:21)
<asynchronous suspension>
#6      withHotreload (package:shelf_hotreload/src/with_hotreload.dart:102:3)
<asynchronous suspension>
[process] Server process has been terminated
StdinException: Error setting terminal line mode, OS Error: 句柄无效。
, errno = 6
PS D:\DartProj\my_project> ^C
PS D:\DartProj\my_project> ^C
PS D:\DartProj\my_project> ^C
PS D:\DartProj\my_project> ^C
PS D:\DartProj\my_project> dart_frog dev
✓ Running on http://localhost:8080 (0.3s)
The Dart VM service is listening on http://127.0.0.1:8181/AhhHKro5uoo=/
The Dart DevTools debugger and profiler is available at: http://127.0.0.1:8181/AhhHKro5uoo=/devtools?uri=ws://127.0.0.1:8181/AhhHKro5uoo=/ws
[hotreload] Hot reload is enabled.
Press either R or r to reload
Unhandled exception:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = ::, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:1032:7)
<asynchronous suspension>
#1      _RawServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:1812:15)
<asynchronous suspension>
#2      _ServerSocket.bind.<anonymous closure> (dart:io-patch/socket_patch.dart:2097:15)
<asynchronous suspension>
#3      _HttpServer.bind.<anonymous closure> (dart:_http/http_impl.dart:3186:27)
<asynchronous suspension>
#4      serve (package:shelf/shelf_io.dart:60:16)
<asynchronous suspension>
#5      withHotreload.<anonymous closure> (package:shelf_hotreload/src/with_hotreload.dart:81:21)
<asynchronous suspension>
#6      withHotreload (package:shelf_hotreload/src/with_hotreload.dart:102:3)
<asynchronous suspension>
[process] Server process has been terminated
StdinException: Error setting terminal line mode, OS Error: 句柄无效。
, errno = 6

**Comment by alestiago** [comment]
HI @Chenlin2020-center thank you for opening this issues 💙 !

Do you mind outlining the steps we need to to follow to reproduce this issue?

**Comment by Chenlin2020-center** [comment]
> HI @Chenlin2020-center thank you for opening this issues 💙 !嗨，感谢您打开本期💙！
> 
> Do you mind outlining the steps we need to to follow to reproduce this issue?您是否介意概述重现此问题所需遵循的步骤？

Thank you, the issue has been resolved. It was a localhost problem. Localhost was not mapped to 127.0.0.1.
