### ISSUE TITLE
feat: add ability to install dart_frog_cli from different package managers

### ISSUE THREAD

**Issue by jorgecoca** [VeryGoodOpenSource/dart_frog#132]
**Description**

In order to make the tool more accessible for non-Dart developers, it'd be interesting to have the ability to install `dart_frog_cli` from different package managers, like [Homebrew](https://brew.sh) or [Chocolatey](https://chocolatey.org).

**Requirements**

- [x] Install using `dart pub global`
- [ ] Install using `brew`
- [ ] Install using `chocolatey`
- [ ] Install using `apt` (Ubuntu)

**Additional Context**

If extra context is needed, we can see how `mason` already supports this: https://github.com/felangel/mason/tree/master/packages/mason_cli#installation

**Comment by SPiercer** [comment]
i'd also recommend npm why not you know :""

**Comment by SPiercer** [comment]
@felangel @jorgecoca i've created a debian installer you can find it in my fork
https://github.com/SPiercer/dart_frog/raw/main/packages/dart_frog_cli/target/dart_frog_0.1.1-1_amd64.deb

along side with an apt repo but it needs your signing and hosting of course.
i tested it with localhost and an example signing key and everything working fine

**Comment by felangel** [comment]
Just for my understanding what would be the advantage of supporting all of these different package managers? 

Dart Frog requires Dart to be installed and `dart pub global activate dart_frog_cli` universally.

**Comment by felangel** [comment]
Closing this for now since I don't think there's any benefit given Dart Frog is designed specifically for the Dart ecosystem. Feel free to comment with any additional context and I'm happy to continue the conversation.
