### ISSUE TITLE
feat: Actor model 

### ISSUE THREAD

**Issue by erlangparasu** [VeryGoodOpenSource/dart_frog#1325]
**Description**

https://en.wikipedia.org/wiki/Actor_model

**Requirements**

- [ ] Implement actor model per request

**Additional Context**

example implementation of actor model: https://actix.rs/

**Comment by tomarra** [comment]
Hi @erlangparasu 👋 Thanks for opening this issue.

As of right now we don't have any plans to put an actor model based approach into Dart Frog. If this is something that you think is valuable please feel free to re-open this issue with some more details and a possible approach that could then be triaged by the team. Until then closing this as a "won't fix"
