### ISSUE TITLE
fix: multiple file structures can make it unclear where code will be executed

### ISSUE THREAD

**Issue by mtwichel** [VeryGoodOpenSource/dart_frog#133]
**Description**

I hesitate to call this a bug because nothing is _broken_, but I think I found a quirk that needs addressed either by changing the code or documenting it somewhere.

You currently can define a route with a file name (`routes/hello.dart`) and with a folder name and `index.dart` (`routes/hello/index.dart`). In this case, it is unclear to the developer which hander will be called, if any.

In my testing, it seems the nested `index.dart` handler will be called. I think this is fine default behavior, but I can imagine that being confusing to someone new with the package if they end up in a weird state like this.

**Steps To Reproduce**

1. Clone [this minimum reproduction](https://github.com/mtwichel/dart_frog_minimum_reproduction)
2. Notice the file structure. We have a hander on `routes/hello.dart` and `routes/hello/index.dart`
3. Run `dart_frog dev` and send a request to `/hello`
4. Notice it says `Hello from hello/index.dart`

**Expected Behavior**

Personally, I would expect this kind of case to display an error in the CLI, and also an error with `dart_frog build`.

I could also see an argument for having this just be the intended behavior (as long as it's consistent), but in that case I really think it should be clearly documented so if someone ends up in that situation and don't understand why a handler isn't being called, it's easy for them to solve their problem.

Thanks VGV 💙  I'm excited to hear what you think.

**Comment by felangel** [comment]
Thanks for opening an issue @mtwichel and yes I agree this should result in an error. I’ll have a fix for this shortly 👍
