### ISSUE TITLE
fix: route not found if you have folder with file under parameter

### ISSUE THREAD

**Issue by dom3lek** [VeryGoodOpenSource/dart_frog#134]
**Description**

Basically, if you have nested folder including parameters the routes are not being found. 

**Steps To Reproduce**

1. Create simple structure: `test/[id]/test2/index.dart`
2. Try to execute the call, the route will not be found. 

**Expected Behavior**

The route should be reachable as `test/$id/test2` and `test/$id/test2/ `

**Additional Context**

The problem does not appear if you put index.dart directly in `[id]` folder.

**Comment by felangel** [comment]
@dom3lek this should be resolved in [dart_frog_cli v0.0.2-dev.8](https://pub.dev/packages/dart_frog_cli/versions/0.0.2-dev.8)

**Comment by dom3lek** [comment]
Thanks, I will give that try.
