### ISSUE TITLE
fix: VSCode failure to start a development server

### ISSUE THREAD

**Issue by ralfeus** [VeryGoodOpenSource/dart_frog#1344]
**Description**
Once a while the button "Start server" disappears from the bottom bar. If I try to start dev server from command menu I get an error: 

>Failed to find a Dart Frog project within the current workspace.

At the same time running `dart_frog dev` works just fine

**Steps To Reproduce**

1. Open command menu (Ctrl + Shift + P)
2. Choose Dart Frog: Start and Debug Development Server
3. See error

**Expected Behavior**

Dev server is started

**Screenshots**
![image](https://github.com/VeryGoodOpenSource/dart_frog/assets/1980527/22409b4d-9ab2-4027-a909-deb959976a5d)

**Additional Context**

OS: MacOS on M1
Dart Frog project is one of 3 in the workspace

**Comment by alestiago** [comment]
Hi @ralfeus thanks for opening an issue! Sorry for not being able to catch-up sooner.

The extension does have some logic to figure out where the Dart Frog server is meant to be. When there are multiple ones, as in your case, you should be prompted to choose between them.

If you open VS Code with the directory that your `dart_frog dev` project is running as the root does it still show the warning?

I would like to reproduce this, can you share the [directory structure](https://stackoverflow.com/questions/3455625/linux-command-to-print-directory-structure-in-the-form-of-a-tree) of your project with the 3 dart frog projects?

**Comment by alestiago** [comment]
Hi @ralfeus ! I'm glad you've figured it out.

I'm waiting for a reply on:
> If you open VS Code with the directory that your dart_frog dev project is running as the root does it still show the warning?

Is there anything that you would like us to do regarding this issue?

**Comment by ralfeus** [comment]
Hi @alestiago,
no, if I open the VS Code with dart_frog project as only one there is no warning and "Start server" is visible no matter what file is selected and it works properly.

**Comment by alestiago** [comment]
Thanks @ralfeus, I am closing this for now then. If anything comes up, don't hesitate on telling.
