### ISSUE TITLE
fix: middlewares wont work with dynamic routes

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/dart_frog#136]
**Description**

Middlewares inside dynamic routes are not recognized.

**Steps To Reproduce**

1. Create a frog server with the following route structure
```
routes/
  - _middleware.dart
  - [id]/
    - index.dart
    - _middleware.dart
```
2. On the root middleware, put the following content:
```dart
import 'package:dart_frog/dart_frog.dart';

Handler middleware(Handler handler) {
  return handler
      .use(provider<String>((context) {
    return 'root middleware haha';
  }));
}
```
3. On the middleware under `/[id]`, put the following content:
```dart
import 'package:dart_frog/dart_frog.dart';

Handler middleware(Handler handler) {
  return handler
      .use(provider<String>((context) {
    return 'id middleware hihi';
  }));
}
```
4. On `/[id]/index.dart`  put the following content:
```dart
import 'package:dart_frog/dart_frog.dart';

Response onRequest(RequestContext context) {
  final thingy = context.read<String>();
  return Response(body: 'result: $thingy');
}

```
5. Start the server and go to `http://localhost:8080/someid`
6. See the result: `result: root middleware haha`

**Expected Behavior**

The handler at `/[id]/index.dart`  should; receive a context with information for the closest middleware, not the root one. 

**Additional Context**

Reproducible with the CLI version `0.0.2-dev.7`

**Comment by felangel** [comment]
related to https://github.com/google/dart-neats/issues/40

**Comment by BeatriceMitchell** [comment]
Descoping from O.1, moving to 1.0
