### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by adepauldami** [VeryGoodOpenSource/dart_frog#1379]
**Description**
After setting my telegram webhook, I could not see the messages been sent from telegram on server, but same procedure worked  with Elysiajs server

**Additional Context**

I guess maybe because it does not support wild card or any route

**Comment by tomarra** [comment]
Hi @adepauldami 👋 Thanks for opening this ticket.

Unfortunately we can't support basic troubleshooting tickets at this time. If you have a more specific bug or request please ensure to add in an example project so it can easily be reproduced and triaged by the team.

Until then, closing this out as "won't fix"
