### ISSUE TITLE
How to modify the entry point (ex: to open a connection with Mongo dart)

### ISSUE THREAD

**Issue by nickscamara** [VeryGoodOpenSource/dart_frog#142]
Hi everyone, thanks for bringing such an amazing framework to the Dart/Flutter community.

I was wondering what would be the best way to modify the entry point to open a connection with Mongo Dart for example. I looked at the youtube demo video and I saw that you generate the entry point in the `build` file only. 

Is there any other way to have specific code run when the server is started?

Thanks.

**Comment by felangel** [comment]
Hi @nickscamara 👋 
Thanks for opening an issue and for the positive feedback!

You should be able to establish a connection and provide an instance of your DB via middleware:

```dart
// routes/_middleware.dart

// Create database client instance and/or establish connection.
// This will be executed once upon startup.
final dbClient = DatabaseClient();

Handler middleware(Handler handler) {
  return handler.use(provider<DatabaseClient>((_) => dbClient));
}
```

Let me know if that helps 👍
