### ISSUE TITLE
Is dart_frog multithreaded by default?

### ISSUE THREAD

**Issue by AlcoholicCoder** [VeryGoodOpenSource/dart_frog#1441]
I would like to utilise all cores in my processor.
Do we have to create Isolates manually?

**Comment by wolfenrain** [comment]
Hey @AlcoholicCoder, Dart Frog isn't multi threaded as it uses Shelf under the hood which isn't using isolates either to handle multiple requests.

**Comment by eraps7** [comment]
@AlcoholicCoder this video may help guide you on how to implement isolates server side https://www.youtube.com/watch?v=eN3UEiuyDpg

**Comment by tomarra** [comment]
Hi @AlcoholicCoder 👋 Thanks for opening this issue.

Based on the information in @wolfenrain's comment I'm going to close this out as won't fix. Given that our implementation is based on Shelf which isn't using isolates we would have to essentially rewrite the core of Dart Frog to allow for this. Overall this isn't a priority for us at this time.
