### ISSUE TITLE
feat: add cookie authentication to dart_frog_auth

### ISSUE THREAD

**Issue by mtwichel** [VeryGoodOpenSource/dart_frog#1589]
### Description

Last week I implemented a cookie based authentication middleware that looked suspiciously like the authentication methods already available in `dart_frog_auth`. The signature is:
```dart
cookiesAuthentication<User>(
          authenticator: (RequestContext context, Map<String, String> cookies) {
            // ... use cookies to authenticate
          }
        ),
```

Is this something we'd be interested in adding to `dart_frog_auth`? I'll probably just open a PR real fast anyway, but wanted follow procedure and open an issue first.

### Requirements

- [ ] All CI/CD checks are passing.
- [ ] There is no drop in the test coverage percentage.
- [ ] Add to authentication docs

**Comment by wolfenrain** [comment]
That would be splendid!

**Comment by mtwichel** [comment]
PR added!
