### ISSUE TITLE
docs: json_serializable only works within lib folder

### ISSUE THREAD

**Issue by novas1r1** [VeryGoodOpenSource/dart_frog#180]
Hey,

I played around with dart_frog today and since I'm used to json_serializable I used it for my models. From a flutter project and dart package perspective it's pretty clear the model files have to be inside the `lib` folder to be json-generated, but from the dart_frog perspective I first did not create a `lib` folder but just created a `models` folder on the same level like the `routes` folder. This might be stupid and totally clear it doesn't work - I don't know - but my json-generation did not generate any files and also did not give me any error message. It took me some time to get to this moment where I was like: "oh... I have to put it inside the lib folder" to make it work.

Is my assumption true by putting it in the lib folder is the only possible way to generate those models or did I miss something or my configuration is broke etc.?

Best regards, keep up the great work <3
Verry

**Comment by renancaraujo** [comment]
In the [dart package conventions](https://dart.dev/tools/pub/package-layout#public-directories), it is mentioned that only two directories in a package (any directory with a pubspec.yaml is a package) are accessible to other packages: `lib` and `bin`. 

I am not sure if that is strict on code generators (eg: `/routes` would be inaccessible even if json_serializable wanted to) but I would assume that at least they are following the convention by expecting that your code is in either of these directories. 

I would also assume that json_serializable is not the only thing in the ecosystem that would create this issue. 

Shall we have a convention (specifically for frog servers) here @felangel ?

**Comment by felangel** [comment]
Closing this for now but feel free to comment with any additional questions and I'm happy to continue the conversation 👍
