### ISSUE TITLE
[proposal] feat: provider's create param should allow asynchronous functions

### ISSUE THREAD

**Issue by mtwichel** [VeryGoodOpenSource/dart_frog#196]
## Description

As a developer, I would like to inject dependencies like so:
```dart
return handler.use(
    provider<SecretManagerApi>((context) async {
        final client = await clientViaApplicationDefaultCredentials(scopes: []);
        return SecretManagerApi(client);
    }),
);
```
However, this will result in a complier error as the `create` function passed to `provider` must be synchronous.

I propose we change the `create` function's definition from 
```dart
T Function(RequestContext context) create
``` 
to 
```dart
FutureOr<T> Function(RequestContext context) create
```
## Pros and Cons
The upside would be that you can write code like the example above. The downside is that it would required the `read<T>` function to return `FutureOr<T>`, which would be a breaking change and required you to `await` every call to `read`.

example:
```dart
Future<Response> onRequest(RequestContext context) async {
  final secretManagerApi = await context.read<SecretManagerApi>();
  return Response();
}
```
I argue that's not a major breaking change because 
1. `dart_frog` is still very young and experimental
2. I would be willing to bet 90% of all `Handler`s are `async` anyway (for reading from a database or calling an external API, for example). Thus, this would just mean adding a few more `await`s in your code.

## Other Workarounds
There are a few workarounds that we've tried that work today:

**1. Inject a `Future` that returns the dependency**
```dart
return handler.use(
    provider<Future<SecretManagerApi>>((context) async {
        final client = await clientViaApplicationDefaultCredentials(scopes: []);
        return SecretManagerApi(client);
    }),
);
```
and to read
```dart
Future<Response> onRequest(RequestContext context) async {
  final secretManagerApi = await context.read<Future<SecretManagerApi>>();
  return Response();
}
```

This works, but I think the syntax of reading a `Future` of a dependency is pretty clunky imo.

**2. A `readAsync` extension on `RequestContext`**
```dart
extension RequestContextAsync on RequestContext {
  Future<T> readAsync<T>() => read<Future<T>>();
}
```
to inject:
```dart
return handler.use(
    provider<Future<SecretManagerApi>>((context) async {
        final client = await clientViaApplicationDefaultCredentials(scopes: []);
        return SecretManagerApi(client);
    }),
);
```
and to read:
```dart
Future<Response> onRequest(RequestContext context) async {
  final secretManagerApi = await context.readAsync<SecretManagerApi>();
  return Response();
}
```

This also works, but imo it would be confusing for new developers to decide when to use `read` and when to use `readAsync`, and it wouldn't be in official documentation.

---

Finally, I have a branch that displays this functionality here: https://github.com/mtwichel/dart_frog/tree/feat/async-create-functions (not PR ready because of testing, but could become so fairly quickly I believe)

I'm curious what everyone thinks! Thanks for everything VGV 💙

**Comment by felangel** [comment]
@mtwichel I'd love your thoughts on #259

**Comment by felangel** [comment]
Closing for now see #259
