### ISSUE TITLE
Prisma like

### ISSUE THREAD

**Issue by nimr77** [VeryGoodOpenSource/dart_frog#214]
during my working on the backend, I used to use Prisma to manage my databases, 
I would like to know how to integrate Prisma or use the same ORM with dart frog,

I will be using this SDK for my personal project to test it and see what we can Improve on it 
So on production, we can switch from nestJS to dart_frog.

**Comment by felangel** [comment]
Hi @nimr77 👋
Thanks for opening an issue! Have you checked out #85? Let me know what you think 👍

**Comment by nimr77** [comment]
Ah ok, yet I think dart_frog is the core of backend developers with dart, I saw your documentation and how it actually works, it's amazing and I'm so excited to start using it, and I'm wondering is there a community for dart backend developers.

so to understand, it will be nodeJS in dart, and we need to have ORM like Prisma, right?

**Comment by felangel** [comment]
Thanks for the positive feedback!

> I'm wondering is there a community for dart backend developers

I'm not sure of any official communities for Dart backend developers but I'm sure you can find some folks using Dart on the backend on Twitter, the Flutter Slack, or Discord.

> so to understand, it will be nodeJS in dart, and we need to have ORM like Prisma, right?

Dart Frog is more analogous to express.js in node.js and hopefully there will be some solid ORMs in the near future.

**Comment by utamori** [comment]
This is what we can expect.
It would be great if dart + prisma could be realized.

https://github.com/prismaorm

**Comment by nimr77** [comment]
> This is what we can expect. It would be great if dart + prisma could be realized.
> 
> https://github.com/prismaorm

Link Error 404
