### ISSUE TITLE
feat: Improve ease of implementation

### ISSUE THREAD

**Issue by dinbtechit** [VeryGoodOpenSource/dart_frog#215]
**Description**

This is a great initiative. But I feel like the implementation is not very intuitive. Have you ever played with a framework called - [nest.js](https://docs.nestjs.com/). It's incredibly straightforward to build production-scale applications. I wish dart_frog could follow a similar pattern. Let me know what you guys think about it. Cheers 🍻

**Requirements**

- [ ] Annotations for controller - endpoints and websockets, 
- [ ] Constructor Injectable services (for inversion of control and Dependency Injection)

**Comment by felangel** [comment]
Hi @dinbtechit 👋 
Thanks for opening an issue!

Yes, many members on our team have experience with nest.js and it's a great framework. We have decided to align more closely with other popular web frameworks like [sveltekit](https://kit.svelte.dev/), [remix.run](https://remix.run), and [next.js](https://nextjs.org/). It would be really helpful if you could elaborate on why you feel the implementation is not intuitive (ideally with some concrete examples/snippets).

In terms of your requirements:

- Annotations for controller endpoints
  - This is supported via file system based routing. You just need to create a file under the routes directory (no need to create controllers with annotations). Websocket support is on the roadmap so stay tuned.
- Constructor injectable services
  - You can use `middleware` with the built-in `provider` middleware to inject instances of Objects to one or more route handlers and resolve them via `context.read<T>()`. I highly recommend checking out the documentation at https://dartfrog.vgv.dev if you haven't already.

Let me know what you think and thanks again for the feedback! 👍

**Comment by felangel** [comment]
Closing for now since there doesn't appear to be any actionable next steps. Feel free to comment with any additional thoughts and I'm happy to continue the conversation 👍
