### ISSUE TITLE
feat: How can I run Dart frog with HTTPS support (SSL)?

### ISSUE THREAD

**Issue by zottel4242** [VeryGoodOpenSource/dart_frog#223]
**Description**

How can I configure dart frog to allow accessing the server via HTTPS? I know that I need to setup the certificate on my server accordingly. However, it seems that I'd also need to adjust how the server is started via shelf? Does dart frog so far support HTTPS connections?

**Comment by felangel** [comment]
Hi @zottel4242 👋 
Thanks for opening an issue!

The easiest way to achieve this is by generating a production build via `dart_frog build` and deploying to a cloud provider which has a container registry. We currently have deployment guides for:

- [Google Cloud Run](https://dartfrog.vgv.dev/docs/deploy/google-cloud-run)
- [AWS App Runner](https://dartfrog.vgv.dev/docs/deploy/aws-app-runner)
- [Digital Ocean App Platform](https://dartfrog.vgv.dev/docs/deploy/digital-ocean-app-platform)

We are planning to support custom entrypoints (#226) for cases where you need to manually configure the initialization of your app.

Hope that helps!

**Comment by felangel** [comment]
You can now use a custom entrypoint (#226) to configure the server 👍
https://dartfrog.vgv.dev/docs/advanced/custom_entrypoint

**Comment by unger1984** [comment]
How can i run Dev Server with custom ssl cert?
