### ISSUE TITLE
fix: Roadmap link returns 404 from verygood.ventures website

### ISSUE THREAD

**Issue by sebastiankutschbach** [VeryGoodOpenSource/dart_frog#239]
**Description**

The roadmap link under https://verygood.ventures/blog/dart-frog points to an invalid url.

**Steps To Reproduce**

1. Go to '[...](https://verygood.ventures/blog/dart-frog)'
2. Click on '[Dart Frog Roadmap](https://github.com/VeryGoodOpenSource/dart_frog/blob/main/ROADMAP.md)'
3. See error 404

**Expected Behavior**

I see the roadmap for dart frog

**Comment by scarletteliza** [comment]
This should be fixed now 👍
