### ISSUE TITLE
Understanding: Using Dart Frog with Discord and Twilio

### ISSUE THREAD

**Issue by Gene-Dana** [VeryGoodOpenSource/dart_frog#243]
**Description**

I'm designing a server for facilitating communication between coordinators and families at https://continual.care and I'm unsure whether or not I'm using this tool correctly.

This is what I'm seeking to do:

![image](https://user-images.githubusercontent.com/45580241/183127208-c816dd85-aae6-4ddd-a7c2-f74cbce8ef97.png)

1. I'm envisioning that we can instance a new server for each conversation, with the inputs of `discord channel` and `phone number.` Logistically, does that make sense? I imagined using something like a brick to generate this.

2. I've read through a few issues

#223
#142 
#226 

and I'm wondering if I'm running into the same issue here : I'm attempting to connect to the discord channel upon startup and it doesn't seem to happen until I visit https://localhost:8080 . Is this because of these referenced issues?

**Comment by felangel** [comment]
Hi @Gene-Dana 👋 
Thanks for opening an issue!

Yes, #226 is blocking you from being able to run arbitrary code on startup. I'm planning to get to this sometime next week but in the meantime I recommend using a piece of middleware to lazily establish a connection and cache the connection for the lifetime of the application. Hope that helps!

**Comment by Gene-Dana** [comment]
Okay ! Does the lazy creation in the middleware mean that this code is fired only once that route is visited?

**Comment by felangel** [comment]
> Okay ! Does the lazy creation in the middleware mean that this code is fired only once that route is visited?

Yes 👍

**Comment by Gene-Dana** [comment]
Is there a way to fire a route without actually visiting it in a browser?

Also, is this a pattern that you would typically avoid? If so, how?

**Comment by felangel** [comment]
> Is there a way to fire a route without actually visiting it in a browser?
> 
> Also, is this a pattern that you would typically avoid? If so, how?

You need to make a request to the server for that endpoint. You can do that via `cURL`, visiting the url in the browser, etc...

**Comment by Gene-Dana** [comment]
Gotcha. This is just temporary anyways, so it doesn't matter too much ! Thanks !
