### ISSUE TITLE
dart_frog create error

### ISSUE THREAD

**Issue by ylahav** [VeryGoodOpenSource/dart_frog#284]
**Description**

After dart_frog_cli installation I tried to create a new project:

`dart_frog` create backend

and go the following error:

✓ Creating backend (0.2s)
Unable to install dependencies for hook: post_gen.dart.
Error: Error on line 1, column 1 of ..\..\..\..\Roaming\Pub\Cache\hosted\pub.dartlang.org\.cache\mocktail-versions.json: Invalid version constraint: Expected version number after ">=" in ">=2.12-0-0 <3.0.0", got "2.12-0-0 <3.0.0".

Using: Dart SDK version: 2.17.6 (stable) (Tue Jul 12 12:54:37 2022 +0200) on "windows_x64"

**Comment by felangel** [comment]
Hi @ylahav 👋
Thanks for opening an issue!

Looks like it’s an issue with your pub cache. Can you try clearing your pub cache via `dart pub cache clean` and re-running `dart packages get`?

**Comment by ylahav** [comment]
Yes, you are right - I removed the cache JSON file and it works now.
Thanks for the quick response
