### ISSUE TITLE
feat: VSCode/IntelliJ support for DartFrog

### ISSUE THREAD

**Issue by iamsahilsonawane** [VeryGoodOpenSource/dart_frog#286]
**Description**

As mentioned in the roadmap, it includes the support for VSCode/Intellij Plugin. I am adding this issue as I think I'll be happy to contribute to this. 

**Requirements**

*From the roadmap points: The extensions will include*
- [x] Create a new project
- [x] New Routes
- [x] New Middleware
- [x] Attach Debugger

**Additional Context**

I'll be very excited and happy to contribute to this project in any way possible, and this proposal fits me quite well.  
Thanks for the great package!

**Comment by felangel** [comment]
Hi @iamsahilsonawane 👋
Thanks for opening an issue!

I would recommend holding off on working on this issue until #260 is done so that the extensions can leverage the CLI and we don’t need the maintain duplicate implementations. Thanks so much for the enthusiasm and support!

**Comment by iamsahilsonawane** [comment]
Sure will wait. 

Let me know if I could start working on this once the CLI with those commands ready!

Thanks 👍

**Comment by felangel** [comment]
> Sure will wait.
> 
> Let me know if I could start working on this once the CLI with those commands ready!
> 
> Thanks 👍

Yes, definitely! 💯

**Comment by rlimberger** [comment]
Is there currently no way to attach the vscode debugger to the dart_frog process?

**Comment by iamsahilsonawane** [comment]
I don't think there is. 

@felangel when can we start on this?

**Comment by felangel** [comment]
@rlimberger yes you can copy the dev tools URL (you’ll see it when you run dart_frog dev) and use the Dart Attach to Process command, paste the url (but you’ll need to remove the url fragment (`#`)).

We are working on making this simpler but the above steps should work in the meantime. Hope that helps!

**Comment by jaumard** [comment]
@felangel not sure what you're saying about `Dart Attach to Process command` I don't have such command on IntelliJ.

**Comment by alestiago** [comment]
A Dart Frog VS Code extension is now available at the [VS Code Marketplace](https://marketplace.visualstudio.com/items?itemName=VeryGoodVentures.dart-frog) :partying_face:.

The current published version supports the ability to create a new project, a new route and a new middleware. The next published version will allow attaching a debugger, see https://github.com/VeryGoodOpenSource/dart_frog/pull/955. Therefore, I'm now closing this issue in favour of [feat: IntelliJ extension support #775](https://github.com/VeryGoodOpenSource/dart_frog/issues/775) to target exclusively IntelliJ support.
