### ISSUE TITLE
feat: Working with multipart:form-data

### ISSUE THREAD

**Issue by aaltynbek** [VeryGoodOpenSource/dart_frog#296]
**Description**

It will be good if dart_frog will work with multipart:form-data, for uploading images or files and for just requests

**Requirements**

- [ ] Adding multipart:form-data
- [ ] Adding support for image upload

**Comment by qrhfz** [comment]
is there a way to get shelf router's `Request` object from frog's `Request`?

**Comment by felangel** [comment]
> is there a way to get shelf router's `Request` object from frog's `Request`?

No, Dart Frog abstracts shelf, shelf is just an implementation detail

**Comment by qrhfz** [comment]
i copied some code from `shelf_multipart` but `Multipart()` constructor ask for shelf's `Request`. ok then 🤷.

**Comment by ushieru** [comment]
You can use **shelf_adapters** to use a Shelf implementation. https://github.com/VeryGoodOpenSource/dart_frog/blob/main/packages/dart_frog/lib/src/shelf_adapters.dart
