### ISSUE TITLE
static file is serving in development, but not in production 

### ISSUE THREAD

**Issue by iAbhishekPatil** [VeryGoodOpenSource/dart_frog#298]
**Description**

I've put a `json` file in `public` directory, it's working on developing server, but after building the production build using `dart_frog build` its says `Route not found`

**dart_frog --version** => 0.1.1

**Comment by felangel** [comment]
Hi @iAbhishekPatil 👋
Thanks for opening an issue!

I’ll investigate this shortly and should hopefully have a fix very soon. Sorry for the inconvenience!

**Comment by felangel** [comment]
@iAbhishekPatil this should be resolved in [Dart Frog CLI v0.1.2](https://pub.dev/packages/dart_frog_cli/versions/0.1.2) 🎉
