### ISSUE TITLE
feat: Deploy to vercel

### ISSUE THREAD

**Issue by chimon2000** [VeryGoodOpenSource/dart_frog#313]
**Description**

_Clearly describe what you are looking to add. The more context the better._

I would like the ability to deploy Dart Frog to Vercel.  Although Vercel is mainly highlighted for use by frontend developers, it can be used to build serverless functions in Node.js, Go, Python, and Ruby, and allows developers to define custom runtimes: https://vercel.com/docs/runtimes#advanced-usage/developing-your-own-runtime

**Requirements**

- [ ] Implement a custom runtime for Vercel

**Additional Context**

_Add any other context or screenshots about the feature request go here._

**Comment by tomarra** [comment]
Doing some ticket cleanup and noticing that this has been open for over a year at this point. If this is something that you are interested in contributing back to the Dart Frog product please open a PR with the needed changes and the team would be able to work through getting those accepted and merged in. At this point though we don't plan on prioritizing this work and will be closing this as a "won't fix".
