### ISSUE TITLE
feat: Vite support

### ISSUE THREAD

**Issue by ushieru** [VeryGoodOpenSource/dart_frog#314]
**Description**
Add vite support.

Issue #90 It seems to me that Vite can be better than a template engine.
I write a Blog to add Vite to Dart Frog [Dart Frog + Vite](https://dev.to/ushieru/fullstack-dart-frog-react-2dic). But it may be a good idea to add it to the CLI.

**Additional Context**
With Vite we can give a flavor more similar to new projects such as Astro, Next, Nuxt, etc. Apart from having the opportunity to work with different frameworks such as React, Vue, Svelte, Lit.

**Comment by tomarra** [comment]
Hi @ushieru 👋 Thanks for opening this issue.

As of right now we are not interested in making any changes to the pipeline and how things are packaged up. Thanks for the suggestion though. If this is something that you are looking for to use in your own projects it would be great to write up a proposal that we can review and see if it makes sense to implement.
