### ISSUE TITLE
feat: router group or api versioning

### ISSUE THREAD

**Issue by ekokurniadi** [VeryGoodOpenSource/dart_frog#315]
**Description**

Hello guys, thank's for create dart_frog.
I think router grouping is very important on backend services, it will be good if dart_frog support router group or api versioning. Like Gin-gonic/gin on Go lang

**Requirements**

- [ ] Add Router Group

**Additional Context**

**Comment by felangel** [comment]
Hi @ekokurniadi 👋 
Thanks for opening an issue!

You can group your routes in Dart Frog by nesting them in a directory. For example, if you create a `routes/v1` and put all of your routes inside the `v1` directory the respective endpoints will all be prefixed with `/v1`. Let me know if that helps 👍

**Comment by ekokurniadi** [comment]
Hi @felangel
Thanks for your response. I think it will be clear now 👍
