### ISSUE TITLE
feat: database migration support

### ISSUE THREAD

**Issue by ekokurniadi** [VeryGoodOpenSource/dart_frog#316]
**Description**

Hy Guys, dart_frog is amazing,i 'am very exited about it. It will be good if dart_frog have functionality for database migration support. Maybe dart_frog should have functionality for migrate a models to table and fields on database. I think it will be helpfully.

**Requirements**

- [ ] Add database migration support
- [ ] Add database migration from models to tables and fields on database

**Additional Context**

**Comment by utamori** [comment]
Personally, I don't expect this feature in Frog.
I prefer a combination of prisma, etc.

https://github.com/odroe/prisma-dart

**Comment by MarkOSullivan94** [comment]
> Personally, I don't expect this feature in Frog. I prefer a combination of prisma, etc.
> 
> https://github.com/odroe/prisma-dart

Well it seems like Prisma doesn't have a migration tool for Dart

> Because Prisma Migrate is complex and changeable, we have not yet determined the official development direction of Prisma for Migrate, coupled with our lack of staff (community contributions are welcome), we do not support it for the time being.

Source: https://prisma.pub/concepts#unsupported-prisma-migrate

Please do correct me if I'm wrong though!

**Comment by GabrielRozendo** [comment]
I've been using [drift](https://pub.dev/packages/drift) (`moor` long time ago) for a few months and I'm enjoying.
The focus is for sqlite mainly, but with really few ajusts, PostgreSQL is working very well for me. 

(unfortunately only sqlite and PostgreSQL are supported  -- in memory too, great for testing)
```
/// An enumeration of database systems supported by drift. Only
/// [SqlDialect.sqlite] is officially supported, all others are in an
/// experimental state at the moment.
enum SqlDialect {
  /// Use sqlite's sql dialect. This is the default option and the only
  /// officially supported dialect at the moment.
  sqlite,

  /// (currently unsupported)
  mysql,

  /// PostgreSQL (currently supported in an experimental state)
  postgres,
}
```


It has a [migration](https://drift.simonbinder.eu/docs/advanced-features/migrations/) tool and I like the syntax (more than prisma).
Take a look: https://drift.simonbinder.eu

**Comment by alestiago** [comment]
Hello @ekokurniadi , sorry for the late reply and thanks for opening an issue! I'm glad you're excited about Dart Frog. Currently, Dart Frog has no first party database support. Therefore, I would personally recommend looking at the alternatives other users have suggested in this discussion to connect, manage and migrate your database.

If you think this issue still holds, feel free to re-open and comment about it 💙 .
