### ISSUE TITLE
test: Create Route with query parameters

### ISSUE THREAD

**Issue by sakura-sakai** [VeryGoodOpenSource/dart_frog#322]
**Description**

I can't find any documentation on how make route with query parameters.

`ex: http://example.com/path?name=Branch&products=[Journeys,Email,Universal%20Ads]
`

**Requirements**

- [ ] Create or update documents.

**Comment by Luckey-Elijah** [comment]
to access query parameter you should access the `Uri` object (`uri` or `url`):
```
Response onRequest(RequestContext context) {
  final name = context.request.url.queryParameters['name'];
  // final name = context.request.uri.queryParameters['name'];
  return Response(body: 'Welcome to Dart Frog, $name!');
}
```
The url `http://localhost:8080/?name=Eljiah` will return:
<img width="488" alt="Screen Shot 2022-09-16 at 10 32 41 AM" src="https://user-images.githubusercontent.com/38171761/190663790-f961bcf3-53e9-4453-a6e1-bfc6129b8153.png">

**Comment by sakura-sakai** [comment]
Thanks for added to the document
