### ISSUE TITLE
fix: hot reload makes instance registered twice when using get_it package

### ISSUE THREAD

**Issue by ekokurniadi** [VeryGoodOpenSource/dart_frog#335]
**Description**

I have some problem when i registered object or instance using get_it, when server is hot reloaded get_it re-registered instance make server stop running

**Steps To Reproduce**

1. Create custom entrypoint
2. Register Instance on Get It
3. Run server
4. Do hot reload

**Expected Behavior**
Instance registered only once

**Screenshots**
![gambar](https://user-images.githubusercontent.com/47097891/191836237-4ffee7ce-f0b1-4743-b758-d1571f37b254.png)

My Get It 
![gambar](https://user-images.githubusercontent.com/47097891/191836460-007b6c86-dbb6-440a-8394-bef9e03cd85a.png)

My Custom Entry Point
![gambar](https://user-images.githubusercontent.com/47097891/191837207-f7c30719-b864-45d3-ac86-365c886a383f.png)

**Additional Context**

**Comment by felangel** [comment]
Hi @ekokurniadi 👋
Thanks for opening an issue!

I’ll take a closer look at this shortly but out of curiosity was there any specific reason why you decided to include get_it instead of using the [built in provider API](https://dartfrog.vgv.dev/docs/basics/dependency-injection) for dependency injection? 

Thanks! 🙏

**Comment by ekokurniadi** [comment]
Hi @felangel 
can I use custom dependency injection like injectable or get_it ?

**Comment by ekokurniadi** [comment]
Hi @felangel 
i will close this issue, Thanks for your response

**Comment by felangel** [comment]
> Hi @felangel
> i will close this issue, Thanks for your response

Did you manage to resolve the issue?

**Comment by GabrielRozendo** [comment]
I had same situation.
Actually I'm using the built in DI for routes but I also have some job runners and those don't have a "api call", just a cron to run after start.

The "problem" (I don't think it is a real problem from dart_frog) is about hot reload, after changes, reload everything, even the "init()".
I figured out 2 options to handle this for me.


1. just a flag to check it 
```dart
  Future<void> init() async {
    if (_didSetup) return;
    _didSetup = true;
...
```

2. use the get it built in verifier:
```dart
    if (!GetIt.I.isRegistered<MySingleton>()) {
      GetIt.I.registerLazySingleton<MySingleton>();
    }
```

**Comment by felangel** [comment]
I'm going to re-open this since it sounds like something that should be supported by Dart Frog's hot reload.

**Comment by SuperMuel** [comment]
I've encountered this problem recently, and as @GabrielRozendo stated, it only occurs after hot reloads. 
As I don't mind about my singletons being instantiated again, I just reset them all after each hot reload :

```dart
Future<HttpServer> run(Handler handler, InternetAddress ip, int port) async {
    await GetIt.I.reset();

    configureDependencies();

    return serve(handler, ip, port);
}
```
---

I'm using Injectable instead of the [built in provider API](https://dartfrog.vgv.dev/docs/basics/dependency-injection) because it simplifies working in multiple environments, and also because of periodic jobs runners that don't have access to a context to read from.

**Comment by felangel** [comment]
related to https://github.com/fluttercommunity/get_it/issues/166

**Comment by marcotrumpet** [comment]
> I had same situation. Actually I'm using the built in DI for routes but I also have some job runners and those don't have a "api call", just a cron to run after start.
> 
> The "problem" is about hot reload, after changes, reload everything, even the "init()". A solution would be dart frog offers a place to "init" server and it should not be called on hot reload, only once on start.
> 
> For now, I figured out 2 workarounds options to handle this for me.
> 
> 1. just a flag to check it
> 
> ```dart
>   Future<void> init() async {
>     if (_didSetup) return;
>     _didSetup = true;
> ...
> ```
> 
>  2. use the get it built in verifier:
> 
> ```dart
>     if (!GetIt.I.isRegistered<MySingleton>()) {
>       GetIt.I.registerLazySingleton<MySingleton>();
>     }
> ```

I used the same get it verifier as you and it did the trick.

**Comment by felangel** [comment]
Closing for now since this does not appear to be directly related to Dart Frog. As folks have mentioned, you can check if an object has been registered already to prevent re-registering.
