### ISSUE TITLE
feat: Custom `x-powered-by` header

### ISSUE THREAD

**Issue by jxstxn1** [VeryGoodOpenSource/dart_frog#336]
**Description**

It would be very nice if Dart Frog would update the `x-powered-by` Header to something like: `Dart with Dart Frog` and or if we would be able to change this header/remove it somehow.

**Requirements**

- [ ] Set x-powered-by
- [ ] add a way to remove this header

**Comment by jxstxn1** [comment]
Nice
Thanks for the fast Implementation 👌

Could we add a method so that Middleware's can change or remove this header👀

**Comment by jxstxn1** [comment]
We can change the header with this, but not remove it.
We need to set the HeaderValue to null if we want to remove it.
So maybe we should set it to null in shelf and set the header custom in dart_frog, so that we can change/remove it on the fly🤔


The following for example is giving you the default:
```dart
import 'package:dart_frog/dart_frog.dart';

Middleware poweredByHeader(String? value) {
  return (handler) {
    return (context) async {
      final response = await handler(context);
      return response.copyWith(
        headers: Map.of(response.headers)
          ..update('X-Powered-By', (_) => value, ifAbsent: () => value),
      );
    };
  };
}

Handler middleware(Handler handler) {
  // `null` to omit the header
  return handler.use(poweredByHeader(null));
}
```

Resulting Response:
`"x-powered-by":"dart with package:dart_frog"`

**Comment by felangel** [comment]
> We can change the header with this, but not remove it. We need to set the HeaderValue to null if we want to remove it. So maybe we should set it to null in shelf and set the header custom in dart_frog, so that we can change/remove it on the fly🤔
> 
> The following for example is giving you the default:
> 
> ```dart
> import 'package:dart_frog/dart_frog.dart';
> 
> Middleware poweredByHeader(String? value) {
>   return (handler) {
>     return (context) async {
>       final response = await handler(context);
>       return response.copyWith(
>         headers: Map.of(response.headers)
>           ..update('X-Powered-By', (_) => value, ifAbsent: () => value),
>       );
>     };
>   };
> }
> 
> Handler middleware(Handler handler) {
>   // `null` to omit the header
>   return handler.use(poweredByHeader(null));
> }
> ```
> 
> Resulting Response: `"x-powered-by":"dart with package:dart_frog"`

If you want to remove the header, you can set it to `null` when calling `serve` in a custom entrypoint:

```dart
import 'dart:io';

import 'package:dart_frog/dart_frog.dart';

Future<HttpServer> run(Handler handler, InternetAddress ip, int port) {
  return serve(handler, ip, port, poweredByHeader: null);
}
```
