### ISSUE TITLE
fix: image from docker file cant't running

### ISSUE THREAD

**Issue by ekokurniadi** [VeryGoodOpenSource/dart_frog#351]
**Description**

Image from docker file can't running if i have public directory on my dart_frog project

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**
![gambar](https://user-images.githubusercontent.com/47097891/193395246-2e68240e-af19-4529-8305-f1a6221af76c.png)

**Additional Context**

**Comment by GabrielRozendo** [comment]
I got that too in past (forgot to open the issue), so it is not something from latest version.
Steps To Reproduce

1. dart pub global activate dart_frog_cli
2. dart_frog --version
> 0.1.6
3. dart_frog create my_project
4. _create the public folder + a simple file.txt_
5. dart_frog dev
6. curl http://localhost:8080/file.txt _works_
7. dart_frog build
8. dart build/bin/server.dart
9. curl http://localhost:8080/file.txt _still working_
10. docker build build + docker run

> 
> Unhandled exception:
> Invalid argument(s): A directory corresponding to fileSystemPath "public" could not be found
> #0      createStaticHandler (package:shelf_static/src/static_handler.dart:50)
> #1      createStaticFileHandler (package:dart_frog/src/create_static_file_handler.dart:7)
> #2      createServer (file:///app/bin/server.dart:17)
> #3      main (file:///app/bin/server.dart:12)
> #4      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297)
> #5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

**Comment by felangel** [comment]
Hi @ekokurniadi 👋
Thanks for opening an issue!

This issue should have been resolved already.

Can you confirm that you’re using the latest version of `dart_frog_cli` by running `dart pub global activate dart_frog_cli` and ensure you’re using the latest version of `package:dart_frog` (dart_frog: ^0.1.6)?

**Comment by ekokurniadi** [comment]
![gambar](https://user-images.githubusercontent.com/47097891/193417661-d9f5b163-ea4d-4ddf-9d88-18883c9963ee.png)
on this project i use dart_frog : ^0.1.2

**Comment by felangel** [comment]
> ![gambar](https://user-images.githubusercontent.com/47097891/193417661-d9f5b163-ea4d-4ddf-9d88-18883c9963ee.png)
> on this project i use dart_frog : ^0.1.2

Can you upgrade to dart_frog: ^0.1.6?

Also, what version of dart_frog_cli are you using (run `dart_frog --version `)? If you’re not on the latest version can you upgrade and try again?

**Comment by ekokurniadi** [comment]
![gambar](https://user-images.githubusercontent.com/47097891/193418514-ad366b74-bd3b-437a-8fe6-bfb696c67fd8.png)
![gambar](https://user-images.githubusercontent.com/47097891/193418528-a5777983-d94c-4bfd-a974-320dde9558b3.png)
dart_frog is already use ^0.1.6, but i got same error

**Comment by felangel** [comment]
> ![gambar](https://user-images.githubusercontent.com/47097891/193418514-ad366b74-bd3b-437a-8fe6-bfb696c67fd8.png) ![gambar](https://user-images.githubusercontent.com/47097891/193418528-a5777983-d94c-4bfd-a974-320dde9558b3.png) dart_frog is already use ^0.1.6, but i got same error

Can you provide a link to a minimal reproduction sample?

**Comment by ekokurniadi** [comment]
sure, https://github.com/ekokurniadi/mahasiswa_api

**Comment by felangel** [comment]
@ekokurniadi thanks I was able to reproduce and should have a fix shortly. Sorry for the inconvenience!

**Comment by ekokurniadi** [comment]
@felangel Thanks, glad to be able to use the dart frog

**Comment by felangel** [comment]
@ekokurniadi this should be resolved now in `dart_frog_cli 0.1.7` 🎉

**Comment by ekokurniadi** [comment]
@felangel amazing, thank you 👍
