### ISSUE TITLE
feat: ensureInitialize feature

### ISSUE THREAD

**Issue by ekokurniadi** [VeryGoodOpenSource/dart_frog#356]
**Description**
Hi @felangel
Would you mind if dart_frog have a feature or method to ensure all dependencies are initialize correctly before server running serve, cause i have a method to initialize database on my main.dart (custom entrypoint). on development application is working correctly, but when i run from docker using docker compose to make containers my dart_frog application and my postgre database, on first running dart_frog application can't connect to my database, i must run command docker-compose up twice to make dart_frog application and database connected. I try to add delay, but isn't solved my issue

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**
This my main.dart
![gambar](https://user-images.githubusercontent.com/47097891/193437368-18b74a3d-608c-45f6-aff0-bb696e476caa.png)
This my app.dart to initialize postgres database and do migrate a models to database
![gambar](https://user-images.githubusercontent.com/47097891/193437387-cd7495eb-6877-41fb-9bc9-b34541479486.png)
This my method to get connection from postgres database
![gambar](https://user-images.githubusercontent.com/47097891/193437483-0e288b71-cfcf-47f7-8ae5-dbb375862199.png)
And this my docker-compose
![gambar](https://user-images.githubusercontent.com/47097891/193437644-0db9fd17-8737-4cfb-90d8-c58eece770e5.png)

Add any other context or screenshots about the feature request go here.

**Comment by felangel** [comment]
Hi @ekokurniadi 👋
Thanks for opening an issue!

The custom entry point allows you to execute whatever code you want before calling serve so you should be able to await any connection initialization there (just like in your snippet). Why is the database connection not established? Did you try to debug your application to see when running in docker whether establishing the connection is failing?

I’m not sure I understand the problem. Can you provide a bit more context?

**Comment by ekokurniadi** [comment]
![gambar](https://user-images.githubusercontent.com/47097891/193437682-0d8df0d5-01cb-4f58-a072-f9a5b03c22d5.png)
On first running using docker compose up i got some error, the application can't connect to the database, i must run docker-compose up twice to make application and database connected

**Comment by felangel** [comment]
This doesn’t seem like a dart frog issue and it sounds more like you need to adjust your docker-compose to use restart on failure with a health check. Check out https://stackoverflow.com/questions/31746182/docker-compose-wait-for-container-x-before-starting-y/41854997#41854997 for more info.

**Comment by ekokurniadi** [comment]
i see, i'am sorry about that, i will try to improve my docker compose before. Thank you

**Comment by felangel** [comment]
No problem! 👍
Closing for now but feel free to comment if you have any follow up questions.

**Comment by ekokurniadi** [comment]
Ok, now my application working nicely on production. Thank you 👍 🥇
