### ISSUE TITLE
feat: add accompanying text in the terminal when running a server

### ISSUE THREAD

**Issue by yasht01** [VeryGoodOpenSource/dart_frog#361]
**Description**
Currently on running the server.dart using this command `dart .\build\bin\server.dart` there is no output in the terminal indicating if the server has started running or not. The user is able to verify if the server is running by verifying if any endpoint is returning a response. The cli can return some text in the terminal indicating whether the server is running along with the base URL of the server.

**Comment by felangel** [comment]
Hi @yasht01 👋 
Thanks for opening an issue and sorry for the inconvenience! This was fixed in Dart Frog CLI v0.2.1 🎉
