### ISSUE TITLE
feat: authentication

### ISSUE THREAD

**Issue by MarkOSullivan94** [VeryGoodOpenSource/dart_frog#37]
**Description**

Firstly, I did see this in the [contributing guide](https://github.com/VeryGoodOpenSource/dart_frog/blob/6f781c7a0d746f7bc93b5eecbe6ca094e52915c1/CONTRIBUTING.md):

> At this time, we welcome bug tickets but will not be accepting feature requests because the roadmap and scope of this project is still being defined.

However I feel this is a very important feature to support.

In order to build a backend which enables users to register and login to your app or to monitor 3rd-party apps API usage of public APIs, authentication needs to be in place.

I would guess that the majority of backends being built would only care about user auth and not care about enabling 3rd party apps to use the APIs.

Some of the different types of authentication which could be added:
* JWT tokens
* Bearer token 
* API keys
* OAuth 

In case it may help with OAuth implementation, I did stumble upon this [OAuth example](https://github.com/martin-robert-fink/oauth_server_demo) in the past which may help inspire the implementation for OAuth support for `dart_frog`.

**Requirements**

- [ ] Authentication support is added
- [ ] Documentation is provided on how to setup authentication

**Comment by iampato** [comment]
What is the plan or the roadmap to add this?

**Comment by felangel** [comment]
Added this to the v1.0.0 milestone based on interest from the community.

**Comment by Gene-Dana** [comment]
Hi there 👋🏼 Found this package out there in the wild ! Perhaps this can be useful

https://github.com/ptrbrynt/frog_auth

**Comment by rddewan** [comment]
please we are waiting for the auth feature

**Comment by vikas-flutter** [comment]
> please we are waiting for the auth feature

Try Spod

**Comment by erickzanardo** [comment]
We have recently introduces a new `dart_frog_auth` package and [added documentation](https://dartfrog.vgv.dev/docs/advanced/authentication) about how to use it.

We will continue to improve in that area, adding more tutorials, examples, and eventually additional auth providers if needed.

Due so, we will be closing this issue, but feel free to open new, more specific ones in case something is needed which is not being covered by the current package/docs.

Thanks!!!
