### ISSUE TITLE
docs: official documentation site

### ISSUE THREAD

**Issue by bozzelliandrea** [VeryGoodOpenSource/dart_frog#39]
**Description**

 it would be a better approach for a new framework or library, to create a documentation repository or a web page containing the official documents for the framework.

contributors can work on the issue or to a new feature and also update the docs, and new users can easly understand how it works

**Requirements**

- [ ] A repository or one branch in the same repo with GHPages

**Comment by MaximilianFlechtner** [comment]
Hey checkout https://github.com/MaximilianFlechtner/dart-frog and https://dart-frog.dev

**Comment by felangel** [comment]
> @felangel Hey checkout https://github.com/MaximilianFlechtner/dart-frog and https://dart-frog.dev

Thanks for taking the time to do this! We weren't planning on creating an official documentation site at the moment since Dart Frog is still in an experimental stage and the API is likely to change quite a bit. If/when things stabilize, it's definitely something we'd love to support!

**Comment by felangel** [comment]
We've created a docs site which you can view at https://verygoodopensource.github.io/dart_frog 🎉 
This is just an initial version and we're planning to spend a lot more time in the coming weeks refining the site.

**Comment by bozzelliandrea** [comment]
Great @felangel ! If you want some help for maintain the docs or writing some examples, give me some issues, i am really intrested to contribute on this framework 😁​
