### ISSUE TITLE
feat: How to read files in the current requested context...

### ISSUE THREAD

**Issue by ammarjavedofficial** [VeryGoodOpenSource/dart_frog#394]
If we try to send a file such as image file in the request then how to get it's name in the current requested context

**Comment by felangel** [comment]
Hi @ammarjavedofficial 👋 
Thanks for opening an issue!

This is a duplicate of #296 and in the meantime I recommend taking a look at https://pub.dev/packages/shelf_multipart for inspiration.

**Comment by ammarjavedofficial** [comment]
Create APIs with Dart Frog Backend Server For Flutter / Dart

[https://ammarjaved.com/create-apis-with-dart-frog-backend-server-for-dart-flutter](https://ammarjaved.com/create-apis-with-dart-frog-backend-server-for-dart-flutter)
