### ISSUE TITLE
fix: Unable to execute hook: pre_gen.dart. Error: 'RouteConfiguration' isn't a type.

### ISSUE THREAD

**Issue by SuperMuel** [VeryGoodOpenSource/dart_frog#397]
**Description**
_Error: 'RouteConfiguration' isn't a type._ when running the project in dev mode or building the project

**Steps To Reproduce**

```
dart pub cache clean
choco uninstall dart-sdk
choco uninstall flutter

// Installing dart 2.18.3
choco install dart-sdk
dart pub global activate dart_frog_cli

dart_frog create dart_frog_test
cd .\dart_frog_test

PS C:\Users\supermuel\dart_frog_test> dart_frog dev --verbose
[meta] dart_frog_cli 0.2.2
[codegen] running pre-gen...
⠋ Serving... (3.2s)Unable to execute hook: pre_gen.dart.
Error: 'RouteConfiguration' isn't a type.
  RouteConfiguration configuration,
  ^^^^^^^^^^^^^^^^^^
```

**Additional Context**

On windows 10, everything was working well until (I think) I ran the command `dart pub cache clean` to solve another problem.
I've tried downgrading to lower dart_frog_cli versions or lower dart-sdk versions. But I get this error every time.
I really can't run nor build any dart_frog project on my machine. 

Please let me know if you have a solution for this. If not, maybe I'll quit Windows.

**Comment by felangel** [comment]
Hi @SuperMuel 👋 
Thanks for opening an issue!

It sounds like there's an issue with your pub cache. I would recommend clearing your pub cache (from dart, flutter, and choco since there can be multiple pub caches on your machine depending on how you have installed flutter/dart) and reinstalling `dart_frog_cli`. I'll try to reproduce this shortly on a windows machine and report back if I'm able to reproduce.

**Comment by SuperMuel** [comment]
Hello @felangel 
Thanks for your quick reaction !

For more context, here are actions I have done while attempting solving the problem :

Tried running `dart pub cache repair` and try to launch the server again, but the same problem occurs again. 

Also : 
- Running `dart pub cache clean`
- Checking that `%LOCALAPPDATA%\Pub\Cache` is empty. This is the only dart cache folder I could find in the [docs](https://dart.dev/tools/pub/glossary#system-cache)
- removed `%LOCALAPPDATA%\Temp\Chocolatey`
- `dart pub global deactivate dart_frog_cli`
- `choco uninstall dart-sdk`

- Reinstall dart 2.18.3 from a [ZIP file](https://dart.dev/get-dart/archive)
- `dart pub global activate dart_frog_cli`

Then when creating the server I get this new error message :
```
~\>dart_frog create dart_frog_server
✓ Creating dart_frog_server (0.1s)
Unable to execute hook: post_gen.dart.
Error: The method 'FutureGroup' isn't defined for the class 'Pool'.
 - 'Pool' is from 'package:pool/pool.dart' ('AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pool-1.5.1/lib/pool.dart').
Try correcting the name to the name of an existing method, or defining a method named 'FutureGroup'.
        _closeGroup = FutureGroup();
```

If I run `dart_frog dev` in the created directory, I get the same error as before. 
```
~\dart_frog_server> dart_frog dev
⠼ Serving... (1.1s)Unable to execute hook: pre_gen.dart.
Error: 'RouteConfiguration' isn't a type.
  final RouteConfiguration configuration;
        ^^^^^^^^^^^^^^^^^^
⠇ Serving... (1.4s)
```

(flutter is no longer installed on my machine, and I can't find any cache folder )

I'll of course post a solution or a workaround if I find one. 

Thanks again Felix !

**Comment by felangel** [comment]
@SuperMuel no problem!

Based on the logs it looks like dart is searching for dependencies in `AppData/Local/Pub/Cache/hosted/pub.dartlang.org/pool-1.5.1/lib/pool.dart`. Can you verify that they exist at that location on your file system?

**Comment by SuperMuel** [comment]
Yes! A good amount of packages appeared in `AppData/Local/Pub/Cache/hosted/pub.dartlang.org`, after `dart pub global activate dart_frog_cli`  (including `pool-1.5.1`)

However, if I open the `pool-1.5.1` directory with VS Code, I notice that 'some packages are out of date'. Running `dart pub get` in this directory results in this :

```
 PS ~\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\pool-1.5.1> dart pub get
Resolving dependencies...
Null check operator used on a null value
package:pub/src/entrypoint.dart 159:60                 Entrypoint.lockFilePath
package:pub/src/entrypoint.dart 102:21                 Entrypoint._loadLockFile
package:pub/src/entrypoint.dart 99:42                  Entrypoint.lockFile
package:pub/src/entrypoint.dart 294:21                 Entrypoint.acquireDependencies.<fn>
package:pub/src/log.dart 428:18                        progress
package:pub/src/entrypoint.dart 288:26                 Entrypoint.acquireDependencies
package:pub/src/command/get.dart 55:22                 GetCommand.runProtected
package:pub/src/command.dart 189:45                    PubCommand.run.<fn>
dart:async                                             new Future.sync
package:pub/src/utils.dart 109:12                      captureErrors.wrappedCallback
dart:async                                             runZonedGuarded
package:pub/src/utils.dart 126:5                       captureErrors
package:pub/src/command.dart 189:13                    PubCommand.run
package:args/command_runner.dart 209:27                CommandRunner.runCommand
package:dartdev/dartdev.dart 231:30                    DartdevRunner.runCommand
package:args/command_runner.dart 119:25                CommandRunner.run.<fn>
dart:async                                             new Future.sync
package:args/command_runner.dart 119:14                CommandRunner.run
package:dartdev/dartdev.dart 66:29                     runDartdev
C:\b\s\w\ir\x\w\sdk\pkg\dartdev\bin\dartdev.dart 11:9  main
This is an unexpected error. The full log and other details are collected in:

    ~\AppData\Local\Pub\Cache\log\pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
Null check operator used on a null value
#0      Entrypoint.lockFilePath (package:pub/src/entrypoint.dart:159:60)
#1      dumpTranscriptToFile (package:pub/src/log.dart:375:50)
#2      PubCommand.run (package:pub/src/command.dart:231:13)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
<asynchronous suspension>
#4      DartdevRunner.runCommand (package:dartdev/dartdev.dart:231:18)
<asynchronous suspension>
#5      runDartdev (package:dartdev/dartdev.dart:66:16)
<asynchronous suspension>
#6      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:11:3)
<asynchronous suspension>
```

It explicitly tells me to open an dart-lang issue, but something tells me that running `dart pub get` in a cached package isn't something I'm _allowed_ to do in the first place. And by the way, the mentioned log file doesn't exists 🤕 

PS: This error happens when running `dart pub get` or `deps`, `outdated`, `upgrade`

Do you think that I should open this issue ?

**Comment by felangel** [comment]
Yeah I'd probably open an issue on `pub` and see if anyone else has seen this before. Are you able to test on a different machine? It definitely sounds like a local dart/flutter installation issue with a corrupt pub-cache.

**Comment by SuperMuel** [comment]
Hello @felangel 
I opened an [issue on pub](https://github.com/dart-lang/pub/issues/3626)

Like I mentioned in my last message, replacing the pool-1.5.1 in the cache folder by a fresh folder found on GitHub didn't solve the problem .

I don't have another window machine to test, but I'll try on a virtual machine shortly. 

I'll come back here if I have some news from the pub issue 

Thanks !

**Comment by SuperMuel** [comment]
Hi,
I succeeded reproducing the issue on a fresh windows installation. I explain it in the [pub cache issue](https://github.com/dart-lang/pub/issues/3626#issuecomment-1301953172)

It's related to [this project ](https://github.com/SuperMuel/Kal/tree/main/server)
Like I said, I'll try to restrict the project to the bare minium to make this issue reproducible.  
But this project uses git and path dependencies. Did you have issues before with these kinds of imports ?

Have a good day!

**Comment by SuperMuel** [comment]
> Hi, I succeeded reproducing the issue on a fresh windows installation. I explain it in the [pub cache issue](https://github.com/dart-lang/pub/issues/3626#issuecomment-1301953172)
> 
> It's related to [this project ](https://github.com/SuperMuel/Kal/tree/main/server) Like I said, I'll try to restrict the project to the bare minium to make this issue reproducible. But this project uses git and path dependencies. Did you have issues before with these kinds of dependencies ?
> 
> Have a good day!

**Comment by felangel** [comment]
@SuperMuel I was able to reproduce the issue and am working on a fix.

**Comment by felangel** [comment]
@SuperMuel this should be fixed in `dart_frog_cli v0.2.4` 🎉 
Let us know if you're still encountering issues after upgrading and sorry for the inconvenience!

**Comment by SuperMuel** [comment]
Hello  @felangel
I updated dart_frog and it's working! Thanks a lot for your engagement 👍

**Comment by SuperMuel** [comment]
Hello  @felangel
I updated dart_frog and it's working! Thanks a lot for your engagement 👍
