### ISSUE TITLE
feat: Pass Through Server (BFF)

### ISSUE THREAD

**Issue by alistairholmes** [VeryGoodOpenSource/dart_frog#398]
**Description**

I'm not sure if this is possible but can I create a pass through server that gets json from another server and then serves the parsed json to my app?

**Requirements**

- [ ] Get JSON from another server
- [ ] Parse the JSON
- [ ] Serve the parsed JSON to an app

**Additional Context**

The inspiration for this comes from the Backend for Frontend pattern -> https://samnewman.io/patterns/architectural/bff/#bff

**Comment by felangel** [comment]
Hi @alistairholmes 👋
Thanks for opening an issue!

Yes, this is the primary way in which we use Dart Frog and I highly recommend it.

Closing for now since there are no actionable steps but feel free to comment with any follow up questions and I’m happy to continue the conversation 👍
