### ISSUE TITLE
feat: minimalistic build result

### ISSUE THREAD

**Issue by Tienisto** [VeryGoodOpenSource/dart_frog#446]
**Description**

Hello,

the current result of `dart_frog build` seems to be overcomplicated and less flexible to me.

I'd like to get the minimal compiled output with one command.

```text
build/
  public/
    - all static files...
  server(.exe)
```

This way it is much easier to use a custom Dockerfile or for production systems where Docker is somehow not available.

**Requirements**

- [ ] A new command or a new flag may be required

**Comment by felangel** [comment]
Hi @Tienisto 👋 
Thanks for opening an issue!

Can you please describe what specifically seems to be overcomplicated or less flexible? The only signifiant difference I notice is that instead of `server.exe`, `dart_frog build` generates `bin/server`. Thanks!

**Comment by Tienisto** [comment]
Thanks for the quick response!

First, I don't understand the purpose non-AOT mode `dart build\bin\server.dart` when we can just run `dart_frog dev` in development and `server.exe` in production.

Secondly, the AOT step is currently only specified in the Dockerfile - but at least it is straightforward to do it manually. Some institutions don't have Docker or are not allowed to use Docker.

Finally, I have a heroku-like environment (dokku specifically). All my web apps have a custom Dockerfile in the project root directory which gets tracked into the git repository. `dart_frog build` creates a `Dockerfile` in the `build` directory which is fine. However, I need to write my own Dockerfile anyways because (1) it needs to be in the git repository, (2) My Dockerfile is a little bit more complicated.

Here is how I would write the Dockerfile (I did not tested this but you should know what I mean)

```Dockerfile
# Vue step
FROM node:16.14.2-alpine3.15 as build-vue
WORKDIR /vue-build

COPY vue/package*.json .
RUN npm i

ADD vue/ .
RUN npm run build

# Dart step
FROM dart:stable AS build-dart
WORKDIR /dart-build

RUN dart pub global activate dart_frog_cli

COPY . .
RUN dart pub get

# we need two commands, but can It be done in one? Like 'npm run build'
RUN dart_frog build
RUN dart compile exe build/bin/server.dart -o build/bin/server

# Final step
FROM scratch
COPY --from=build-dart /dart-build/build/bin/server /app/server
COPY --from=build-vue /vue-build/dist/ /app/public/

# Start server.
CMD ["/app/server"]
```

**Comment by Tienisto** [comment]
Diving deeper into the docs. dart_frog already has a handling of custom Dockerfiles! :)

The only thing I think would be nice is a command which does build + AOT in one command producing a minimum result without any dart files. Like `dart_frog --aot`

**Comment by felangel** [comment]
Hi @Tienisto 👋 

We discussed this a big more internally and have decided to hold off on this because:

- The desired functionality can be achieved by running dart compile with your desired flags (this is not a blocker)
- Supporting this would require us to essentially expose a command that proxies to dart compile (along with all options, flags, etc.) which introduces additional complexity that is hard to justify at this stage of the project

Hopefully that makes sense and we're happy to revisit this again in the future and/or continue the discussion, thanks! 👍
