### ISSUE TITLE
docs: Add documentation on how to stop dart_frog server

### ISSUE THREAD

**Issue by Wizzel1** [VeryGoodOpenSource/dart_frog#447]
**Description**

I would love to know how to stop a dart_frog server. I think it would be useful to include this in the docs.

**Comment by felangel** [comment]
Hi @Wizzel1 👋 
Thanks for opening an issue!

You can stop the dev server via Control-C.
This sends the SIGINT signal to the Dart Frog CLI and shuts down the server.

Let me know if that helps! 👍

**Comment by Wizzel1** [comment]
@felangel yes that helps. Thank you very much!
