### ISSUE TITLE
fix: dart_frog update does't update 

### ISSUE THREAD

**Issue by Wizzel1** [VeryGoodOpenSource/dart_frog#449]
**Description**

I am trying to update dart_frog but for some reason it doesn't update, even when I launch the terminal in admin mode.

**Screenshots**

![Unbenannt](https://user-images.githubusercontent.com/43343510/207871184-520ac5fd-22f0-436d-8372-8df7c4d42bc2.PNG)

**Comment by felangel** [comment]
Hi @Wizzel1 👋
Thanks for opening an issue!

Can you confirm you have a supported version of dart installed? (>=2.17.0)

**Comment by Wizzel1** [comment]
@felangel thanks for your quick response!
I am running dart 2.17.5: 

![Unbenannt](https://user-images.githubusercontent.com/43343510/207894048-73cd0b80-4aa0-4dda-a019-f093cb46e2f2.PNG)

**Comment by felangel** [comment]
> @felangel thanks for your quick response! I am running dart 2.17.5:
> 
> ![Unbenannt](https://user-images.githubusercontent.com/43343510/207894048-73cd0b80-4aa0-4dda-a019-f093cb46e2f2.PNG)

Thanks! Can you also provide the output of `flutter doctor --verbose`?

**Comment by Wizzel1** [comment]
I am using fvm to manage my flutter versions, so I don't have a global flutter installation.

**Comment by felangel** [comment]
> I am using fvm to manage my flutter versions, so I don't have a global flutter installation.

If you run `dart pub global activate dart_frog_cli` does that work?

**Comment by felangel** [comment]
Sorry I forgot we upgrade to Dart >2.18.0 so I think you just need to upgrade Dart.

**Comment by Wizzel1** [comment]
You are right, upgrading dart to 2.18.0 solved the problem. Thanks!
