### ISSUE TITLE
fix: Error when trying to set environment variables

### ISSUE THREAD

**Issue by Wizzel1** [VeryGoodOpenSource/dart_frog#451]
**Description**

I am trying to set environment variables with `dart run --define=TEST_KEY=test_value` but it throws an error: 
` Could not find "bin\server_test_project.dart" in package "server_test_project".`

**Expected Behavior**

I expected to be able to access the environment variable with `String.fromEnvironment()`

**Comment by felangel** [comment]
Hi @Wizzel1 👋
Thanks for opening an issue!

This looks like it’s related to #302 but can you provide a bit more context regarding the steps you are taking? Are you running dart_frog dev or are you doing a build and then running the production build with defined environment variables?

**Comment by Wizzel1** [comment]
@felangel I only created the project with `dart_frog create server_test_project`. 
After that I  tried to define environment variables with `dart run --define=TEST_KEY=test_value` and I got the error. 

I haven't added or deleted any files from the folder.

**Comment by felangel** [comment]
> @felangel I only created the project with `dart_frog create server_test_project`. After that I tried to define environment variables with `dart run --define=TEST_KEY=test_value` and I got the error.
> 
> I haven't added or deleted any files from the folder.

To run the project in development mode you need to run dart_frog dev and to run a production build you can run dart_frog build. 

I’m guessing what you want to do is generate a build (dart_frog build) and then run it via dart run which can be done via dart run build/bin/server.dart. Let me know if that helps.

**Comment by Wizzel1** [comment]
@felangel Thanks but the problem is not, that I am not able to run the server. I am not able to set environment variables. 

I am looking to do something like this 

```dart
 JWT.verify(accessToken, process.env.JWT_SECRET);
```
but in dart. Sorry, I haven't set an environment variable in dart before. I only know that in node.js this can be done with an .env file.

**Comment by felangel** [comment]
> @felangel Thanks but the problem is not, that I am not able to run the server. I am not able to set environment variables.
> 
> I am looking to do something like this
> 
> ```dart
>  JWT.verify(accessToken, process.env.JWT_SECRET);
> ```
> 
> but in dart. Sorry, I haven't set an environment variable in dart before. I only know that in node.js this can be done with an .env file.

You can use something like https://pub.dev/packages/dotenv but we plan to improve support for environment variables in the near future.

**Comment by Wizzel1** [comment]
@felangel awesome, can't wait for that. Keep up the amazing work, I am very excited for dart_frog!
