### ISSUE TITLE
Working with Flutter/Dart Full Stack

### ISSUE THREAD

**Issue by sunilmishra** [VeryGoodOpenSource/dart_frog#452]
My project structure is like:
my-project
- Packages
      - fakyClient
      - server
      - shared
 
while using `shared` library inside server, it's showing below message.

```
All path dependencies must be within the project.
External path dependencies detected:
  • shared from ../shared

```
Please suggest me the solution?

**Comment by felangel** [comment]
Hi @sunilmishra 👋
Thanks for opening an issue!

I recommend:

my_project
  server
    packages
      shared

You can still depend on shared from my_project as well but this way the server will contain all the source code it needs. Let me know if that helps!

**Comment by sunilmishra** [comment]
I got it.  Thank you!!
for my curiosity, What could be the reason of `Not allowing external path dependencies`? will there be any issue while deploying using Docker, if there is external path?

**Comment by felangel** [comment]
> I got it. Thank you!!
> 
> As `dart_frog` depends upon `shelf`. `shelf` allowing external path dependencies. e.g https://github.com/flutter/samples/tree/main/code_sharing
> 
> for my curiosity, What could be the reason of `Not allowing external path dependencies`? will there be any issue while deploying using Docker, if there is external path?

Yeah exactly, external paths will not be part of the Docker context.
