### ISSUE TITLE
feat: broadcast to only selected client

### ISSUE THREAD

**Issue by Anas35** [VeryGoodOpenSource/dart_frog#458]
**Description**

Are there a way to group a selected client and broadcast only within that group ? Client that are not in the group should no listen to the message.

[socket.io JS](https://socket.io/docs/v4/server-api/#socketjoinroom) packages uses `join()` and `to()` to broadcast within a group.

**Comment by felangel** [comment]
To broadcast to a specific client you can just add the message to the specific client’s sink. Regarding groups, that is something that you would have to implement currently.

**Comment by Anas35** [comment]
thanks! I implemented the groups by storing the client's sink to its corresponding group id's in a `map`. May be, Groups feature is more suitable for `broadcast_bloc`?

**Comment by felangel** [comment]
> thanks! I implemented the groups by storing the client's sink to its corresponding group id's in a `map`. May be, Groups feature is more suitable for `broadcast_bloc`?

No problem!
Yup, I think it would be great to move this conversation to the broadcast_bloc repository since it more directly pertains to that package, thanks!

**Comment by Anas35** [comment]
Sure, Can you transfer this issue to the `broadcast_bloc` repository or do we have to create a new issue in that repository?

**Comment by felangel** [comment]
Unfortunately, I can't transfer the issue because the broadcast_bloc repository isn't part of the same GitHub organization.

**Comment by Anas35** [comment]
closing on https://github.com/felangel/broadcast_bloc/issues/2

**Comment by aytunch** [comment]
> To broadcast to a specific client you can just add the message to the specific client’s sink. Regarding groups, that is something that you would have to implement currently.

@felangel how do we add a message to a specific client's sink? Do we have a pointer to each connected client? Which variable holds this info? thanks

**Comment by felangel** [comment]
@aytunch each time a new client connects you get a channel object which corresponds to the client and allows you to send/received messages with that specific client. Hope that helps 👍
