### ISSUE TITLE
fix:`Bad state: context.read<T>() called with a request context that does not contain a T`

### ISSUE THREAD

**Issue by saileshbro** [VeryGoodOpenSource/dart_frog#461]
**Description**

I am experiencing an issue with dependency injection in my application. I have followed the documentation to register the `DatabaseConnection` dependency, but when I try to read the dependency using `context.read<DatabaseConnection>()`, I receive the error
```
Bad state: context.read<DatabaseConnection>() called with a request context that does not contain a DatabaseConnection.
```

**Steps To Reproduce**

1. Cloned the repository at the following link: https://github.com/saileshbro/full_stack_todo_dart/tree/main/backend
2. Followed the documentation to register the `DatabaseConnection` dependency.
3. Attempted to read the DatabaseConnection dependency using `context.read<DatabaseConnection>()`.

**Expected Behavior**

I expected that reading the DatabaseConnection dependency using `context.read<DatabaseConnection>()` would return an instance of the `DatabaseConnection` class.

**Screenshots**

https://user-images.githubusercontent.com/43571990/210059225-91eed06a-3e76-422f-82ab-5a4faa2e1edc.mov

**Additional Context**

I am using dart_frog version  `dart_frog: ^0.3.0`.
The relevant code can be found at the following link: https://github.com/saileshbro/full_stack_todo_dart/tree/main/backend

**Comment by saileshbro** [comment]
@felangel Let me know if I am missing anything here 😁

**Comment by felangel** [comment]
Hi @saileshbro 👋
Thanks for opening an issue!

I believe you just need to change `handler..use(provider(…))` to hander.use(provider(…))

**Comment by saileshbro** [comment]
@felangel this world🚀.
Thanks for the heads up💯
