### ISSUE TITLE
feat: be able to read body more than once on Request and Response

### ISSUE THREAD

**Issue by jaumard** [VeryGoodOpenSource/dart_frog#468]
**Description**

I'm trying to add body validation on middleware level for both Request and Response, but look like those can be read only once which make the server crash the second time you want to read.

**Requirements**

- [ ] being able to read request body multiple time
- [ ] being able to read response body multiple time

For the request one workaround would be to read it and then provide it frog dependancy injection but didn't manage to make it work for now.

For response I have no workaround as it will be read by shelf to send back the response anyway, is there a way to duplicate the response so I can read the body in a safe way?

**Comment by jaumard** [comment]
I've checked the source of Request and Response and look like all body methods are just proxies to shelf request and response. So it should be relatively easy to add some caching inside those classes to:
- on request read body from shelf request and cache it for later body calls
- on response cache body at response creation and use it on frog response body methods, that will let the shelf response safe to read it once to send it to the client.

What do you think?

**Comment by felangel** [comment]
> I've checked the source of Request and Response and look like all body methods are just proxies to shelf request and response. So it should be relatively easy to add some caching inside those classes to:
> 
> * on request read body from shelf request and cache it for later body calls
> * on response cache body at response creation and use it on frog response body methods, that will let the shelf response safe to read it once to send it to the client.
> 
> What do you think?

I just opened a pull request to add this functionality. Take a look at #470 and let me know if you have any feedback, thanks! 🙏
