### ISSUE TITLE
spike: investigate ways to support packages which hook into the codegen step

### ISSUE THREAD

**Issue by felangel** [VeryGoodOpenSource/dart_frog#474]
As a developer, I want to be able to write a Dart Frog package which is able to integrate into the Dart Frog build step and affect the generated output so that I can provide valuable functionality without having to contribute to the core Dart Frog package directly.

Examples:

Client Generation: it would be nice to be able to create a separate, standalone package to handle client generation in Dart Frog without having to bloat the core package

Open API Generation: it would be nice to be able to create a separate, standalone package to handler open api documentation generation in Dart Frog without having to bloat the core package

WebSockets: if this capability were available, it would allow for improvements to the Dart Frog WebSocket API like:

```dart
FutureOr<void> onSocketConnection(channel, protocol) async {...}
```

**Comment by renancaraujo** [comment]
Hello, after some research I created [this design doc](https://verygoodventures.notion.site/Design-doc-hooking-on-codegen-6215f26683f24a2eab2daddb3c7e8fed?pvs=4) with some gameplan for to happen. 

In summary, it is possible to create a plugin system for dart frog.

**Comment by tomarra** [comment]
We have the documentation written up for this so closing this as "Complete". Need to figure out prioritization next.
