### ISSUE TITLE
feat: Ability to read providers defined in previous middleware

### ISSUE THREAD

**Issue by chanan** [VeryGoodOpenSource/dart_frog#475]
**Description**

I would like to define a database pool in the "root" middleware. Inside my route middleware I would like to get a reference to it and pass it to my datasource which I will be defining in that route middleware

```
routes
  _middleware.dart // define PgPool provider here
  account
    _middleware.dart //read PgPool and pass it to PostgresAccountDataSource
    index.dart // read PostgresAccountDataSource here
```

**Requirements**

- [ ] Ability to read a previously defined object in a middleware

**Comment by felangel** [comment]
Hi @chanan 👋 
Thanks for opening an issue!

That should already be possible.
Can you please share a link to a minimal reproduction sample that we can take a look at? Thanks!

**Comment by chanan** [comment]
@felangel I can work on one yes, but before I do can you tell me when you say it can already be done, how do you mean?

```
Hander middleware(Handler handler) {
  final pool = context.read<PgPool>(); // This context does not have a read method
}
```

**Comment by felangel** [comment]
@chanan you should be able to do something like:

```dart
Handler middleware(Handler handler) {
  return (context) async {
    final pool = context.read<PgPool>();
    final response = await handler(context);
    return response;
  };
}
```

**Comment by chanan** [comment]
That worked thanks! Below is the full middleware in case anyone has a similiar issue:

```
Handler middleware(Handler handler) {
  return (context) async {
    final pool = context.read<PgPool>();
    final response = await handler.use(accountDataSource(pool))(context);
    return response;
  };
}

Middleware accountDataSource(PgPool pool) {
  return provider<AccountDataSource>(
    (context) => PostgresAccountDataSource(pool: pool),
  );
}
```
