### ISSUE TITLE
feat: Dynamic nested routes

### ISSUE THREAD

**Issue by chanan** [VeryGoodOpenSource/dart_frog#476]
**Description**

Implement dynamic nested routes similar to remix-run.

For example, the below structure should work:

```
routes
  accounts
    index.dart
    [accountId].dart
    [accountId]  // <-- This is a folder
      users
        index.dart
        [userId].dart
```

Which should then map to the following calls:

```
GET http://localhost:8080/accounts/1/users
GET http://localhost:8080/accounts/1/users/1
...
```

and in code:

```
FutureOr<Response> onRequest(RequestContext context, String accountId, String userId) async {
  ...
}

```

**NOTE** The variable names can't be the same because they get put into the same function call (unless some other implementation is implemented).

**Requirements**

- [ ] Dynamic nested routing works

**Additional Context**

* Remix run dynamic route documentation: https://remix.run/docs/en/v1/guides/routing#dynamic-segments
* Should other parts of remix's routing be taken as well such as splat routes?

**Comment by felangel** [comment]
Hi @chanan 👋 
Thanks for opening an issue!

This should already be supported in Dart Frog.

The following directory structure:

```
routes
  accounts
    index.dart
    [accountId]
      index.dart
      users
        index.dart
        [userId].dart
```

Would support the following endpoints:

```
GET http://localhost:8080/accounts/1/users
GET http://localhost:8080/accounts/1/users/1
```

Let me know if that helps and also refer to the documentation on [route conflicts](https://dartfrog.vgv.dev/docs/basics/routes#route-conflicts-) for more information.

**Comment by chanan** [comment]
Yes, you are right when I tried it, I forgot about the route conflicts.

The documentation could be updated to explicitly reflect this scenario, as I think it's fairly common one.

**Comment by felangel** [comment]
> Yes, you are right when I tried it, I forgot about the route conflicts.
> 
> The documentation could be updated to explicitly reflect this scenario, as I think it's fairly common one.

Awesome, glad you got things working! When route conflicts are detected, the Dart Frog CLI should report them as warnings. Do you feel it’s easy to miss the warnings or have suggestions for how to make this more visible? Thanks!

**Comment by chanan** [comment]
I did actually miss it, but I was referring to adding a section in the routing page about dynamic nested routes.

**Comment by felangel** [comment]
> I did actually miss it, but I was referring to adding a section in the routing page about dynamic nested routes.

Got it, I’ll make sure to address this tomorrow. Thanks again!
