### ISSUE TITLE
feat: Able to identify Dart on dart_frog projects using Android Studio

### ISSUE THREAD

**Issue by marcellocamara** [VeryGoodOpenSource/dart_frog#477]
**Description**

When I create a dart_frog project, on Android Studio, the IDE don't identify dart and because of that I can't see the code, the syntax, etc.

**Requirements**

- [x] Create a project on Android Studio
- [ ] Try to resolve the Dart warning to index files and correct syntaxes

**Additional Context**

![Captura de Tela 2023-01-19 às 00 11 22](https://user-images.githubusercontent.com/18273071/213346853-6c4fb813-2c06-4782-93ed-93ac4c2cf216.png)
![Captura de Tela 2023-01-19 às 00 14 03](https://user-images.githubusercontent.com/18273071/213347039-4051d7e3-b662-4011-8dd8-1036104e4802.png)

Only when I create dart_frog projects this issue appears. Anyone has this issue too ?

**Comment by marcellocamara** [comment]
I saw that have a simular issue opened #286

I wonder if it might be a problem, because it's opened **since august 22** 😢 
If I can't see the syntax and the code, how would I use it ?

**Comment by felangel** [comment]
Hi @marcellocamara 👋
Thanks for opening an issue!

#286 is tracking us adding an extension/plugin that will make it easier to generate new routes/middleware/etc from your IDE. You should have no issue editing the code in android studio. Can you provide more context regarding what specifically is not working with details reproduction steps? Thanks!

**Comment by marcellocamara** [comment]
So, after comparing to another flutter project, I found that it was necessary to manually set the dart sdk path 
My previous firts screen shows that I was setting the wrong path

Now it works, my bad 🙏🏻 
![Captura de Tela 2023-01-19 às 09 39 43](https://user-images.githubusercontent.com/18273071/213445576-6abb1400-05de-4b19-b319-c2ab3024b671.png)
