### ISSUE TITLE
feat: Allow IPv6 bind/configuration

### ISSUE THREAD

**Issue by rubenferreira97** [VeryGoodOpenSource/dart_frog#479]
**Description**

Currently dart_frog defaults to `final ip = InternetAddress.anyIPv4;`

Maybe change the default to `anyIPv6` since it accepts both IPv4 and IPv6?

From [docs](https://api.dart.dev/stable/2.1.1/dart-io/HttpServer/bind.html):

> To allow for incoming connection from the network use either one of the values [InternetAddress.anyIPv4](https://api.dart.dev/stable/2.1.1/dart-io/InternetAddress/anyIPv4.html) or [InternetAddress.anyIPv6](https://api.dart.dev/stable/2.1.1/dart-io/InternetAddress/anyIPv6.html) to bind to all interfaces or the IP address of a specific interface.
> 
> If an IP version 6 (IPv6) address is used, both IP version 6 (IPv6) and version 4 (IPv4) connections will be accepted. To restrict this to version 6 (IPv6) only, use v6Only to set version 6 only.

For configuration a possible solution might be to pass the ip like `dart_frog dev --port=8080 --ip=0.0.0.0` or `dart_frog dev --port=8080 --ip=::` but that might be a little awkward.

For now I am using a custom entrypoint with `serve(handler, InternetAddress.anyIPv6, port)`.
However found a little bug:

```dart
Future<HttpServer> run(Handler handler, InternetAddress ip, int port) {
  return serve(handler, InternetAddress.anyIPv6, 8081);
}
```

This logs `Running on http://localhost:8080` instead of `Running on http://localhost:8081` but correctly listens to 8081 port.

**Comment by rubenferreira97** [comment]
@felangel I still did not test it but looking to #525 is this the correct fix? Listening to `localhost` (which translate to `127.0.0.1` or `::1`) is different from listening to `0.0.0.0` or `::` (all interfaces). https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

**Comment by felangel** [comment]
> @felangel I still did not test it but looking to #525 is this the correct fix? Listening to `localhost` (which translate to `127.0.0.1` or `::1`) is different from listening to `0.0.0.0` or `::` (all interfaces).
> Better explanation of the problem:
> https://stackoverflow.com/questions/20778771/what-is-the-difference-between-0-0-0-0-127-0-0-1-and-localhost

This change leaves it up to the lookup API to determine whether to use IPv4 or IPv6 which I believe is a better default behavior. In addition, I’m going to push a fix so that logging is correct when using a custom entrypoint with a custom address and port.

**Comment by rubenferreira97** [comment]
As far as I know listening to `localhost` only correctly chooses IPv4 or IPV6 within the **same host**. 

Quoting from stackoverflow (but using for example `fastify.js` I have the same behavior):

> Imagine that you run any web server (e.g. Nginx) on a remote machine so that you want anyone on the Internet could access it.
> 
> If your Nginx web server listens to 127.0.0.1:80 then nobody could access it beside you logged on this server.
> 
> In case when web server listens to 0.0.0.0:80 anybody on the Internet is able to connect to your server by typing in browser your server IP address.

That means that the server can't be reached "from outside".
