### ISSUE TITLE
fix: Dependency Injection not working on Custom Server Entrypoint `run`

### ISSUE THREAD

**Issue by rubenferreira97** [VeryGoodOpenSource/dart_frog#481]
**Description**

I don't know if this a bug per say or a feature request. It would be awesome to declare dependencies on `run`. Currently is not possible since it throws `Bad state: context.read<String>() called with a request context that does not contain a String.`

**Steps To Reproduce**

```dart
// main.dart
Future<HttpServer> run(Handler handler, InternetAddress ip, int port) {
  handler.use(provider<String>((context) => 'Welcome to Dart Frog!'));
  return serve(handler, ip, port);
}
```

```dart
// routes/index.dart
Response onRequest(RequestContext context) {
  final greeting = context.read<String>();
  return Response(body: greeting);
}
```

**Expected Behavior**

Get `greeting` value and reply with 200 OK and `Welcome to Dart Frog!`.

**Comment by luisgustavoo** [comment]
I'm having the same error. I'm following the documentation tutorial (Counter).

<img width="1152" alt="image" src="https://github.com/VeryGoodOpenSource/dart_frog/assets/59834387/d51e1001-4d14-4582-bba1-6d26511a1a1c">
<img width="600" alt="image" src="https://github.com/VeryGoodOpenSource/dart_frog/assets/59834387/498b1460-6c9a-4a02-b5a5-2bb4e8ee62d2">

<img width="324" alt="image" src="https://github.com/VeryGoodOpenSource/dart_frog/assets/59834387/8bb85c7c-b46b-4df9-81c5-a7be0cafe0a2">

**Comment by rubenferreira97** [comment]
@luisgustavoo It seems you are registering your dependency in the wrong place. I think you just want to move `_middleware` to the `routes` folder and delete the `middleware` folder.

Currently only routes that start with `localhost:8080/middleware` will have access to the counter.

Looking at your file tree you can see that :

- index.dart (asking for a <int> dependency)
- middleware (folder)
  - _middleware (injecting a <int> dependency)
  - if you had a index.dart here you could access it with `context.read<int>()`
  - anotherfolder (folder)
    - if you had a index.dart here you could access it with `context.read<int>()`

**Comment by luisgustavoo** [comment]
Thank you very much
