### ISSUE TITLE
feat: enable SSL for production

### ISSUE THREAD

**Issue by Kephas3** [VeryGoodOpenSource/dart_frog#487]
**Description**

Enable SSL configuration

the solution might be to be able to pass a SecurityContext to the serve function in serve.dart.

**Requirements**

I think that should be configurable in CLI commands for build production only.

dart_frog build --cert <path to certificate> --key <path to private key>

server port should be 443 automatically

**Additional Context**

the feature would securise communication between the reverseproxy and the dart_frog VM. (required by some companies policy)

**Comment by wolfenrain** [comment]
Since the release of v0.3.5 you can now manage the [security context yourself](https://dartfrog.vgv.dev/docs/advanced/security_context). Does this solve your use case?

**Comment by wolfenrain** [comment]
Closing this issue as you can solve it with what I mentioned above, if you have any other questions please open a new issue <3
