### ISSUE TITLE
fix: Deploying with Elastic Beanstalk

### ISSUE THREAD

**Issue by marcellocamara** [VeryGoodOpenSource/dart_frog#488]
**Description**

As I'm new on this backend world, I was discouraged to follow the documentation to deploy using those 3 recommendations (AWS App Runner, Google Cloud Platform and Digital Ocean App Platform) due to it's price. It's unpraticable to deploy with an application 24/7. 
So, because of this, I'm trying to deploy it on EC2 instance, using the Elastic Beanstalk to admistrate the contained app using this build folder .zip generated. But, I didn't get success on it. Could you help on it?

**Steps To Reproduce**

1. Build a new application and .zip the content under build folder
2. Upload this .zip file into the Elastic Beanstalk environment with a docker app.

**Expected Behavior**

Application success deployed.

**Screenshots**

![Captura de Tela 2023-01-28 às 16 30 52](https://user-images.githubusercontent.com/18273071/215287460-90f1b83b-797e-485c-a545-63a33f2afec2.png)

Reading the log error, it seems like not founding the Dockerfile archive. 

`Instance deployment: Both 'Dockerfile' and 'Dockerrun.aws.json' are missing in your source bundle. Include at least one of them. The deployment failed.`

But it's there:
![215287614-3e2ef0a3-0f5e-41a1-9fdf-03525c9b45a8](https://user-images.githubusercontent.com/18273071/215287755-63defb39-0a80-4ebc-94a1-57187b6f18b2.jpg)

**Additional Context**

Docker running on 64bit Amazon Linux 2 - WebServer
t2.micro instance

**Comment by marcellocamara** [comment]
After reading [this](https://phpsolved.com/aws-elastic-beanstalk-invalid-yaml-or-json-error-when-uploading-zip-file-from-mac-os/) I'm getting another error:

`zip -d file.zip __MACOSX/\*`
![Captura de Tela 2023-01-28 às 17 06 58](https://user-images.githubusercontent.com/18273071/215288668-3e3ac090-c072-4c13-a160-a4a665f76497.png)

Deploying the new .zip file:
![Captura de Tela 2023-01-28 às 17 06 45](https://user-images.githubusercontent.com/18273071/215288651-1a3c1211-bee3-4753-9323-d0200adbfcaa.png)

**Comment by marcellocamara** [comment]
I was able to run the project locally, but it doesn't work on AWS Elastic Beanstalk

![Captura de Tela 2023-01-28 às 19 12 45](https://user-images.githubusercontent.com/18273071/215293480-a7638eb9-480f-4e0d-9ea7-a657e3c2dc11.png)

**Comment by marcellocamara** [comment]
I manually created an EC2 instance, installed nginx, docker, etc, and deployed the application.

I couldn't deploy it, with the build folder zip file, using Elastic Beanstalk. if you could try that would be great to see what's wrong

**Comment by felangel** [comment]
Hi @marcellocamara 👋 
Thanks for opening an issue!

I'm going to close this as this isn't directly related to Dart Frog. Dart Frog generates a Dockerfile and you should refer to official documentation for how to deploy dockerized applications to elastic beanstalk.
