### ISSUE TITLE
Need doc to deploy on Goocle Cloud with MySQLDB

### ISSUE THREAD

**Issue by rddewan** [VeryGoodOpenSource/dart_frog#496]
Hi
I have create a simple API for ToDo app with MySQL as database. I need some doc to deploy it to GC with database like accessing the Cloud Run env variables etc.
If nay one have deployed it successfully please share 
Thank you

**Comment by mtwichel** [comment]
This answer is for Postgres and not mySql, but may be a similar story: https://github.com/isoos/postgresql-dart/issues/45

**Comment by felangel** [comment]
Hi @rddewan 👋 

I'm going to close this because it's not directly related to Dart Frog. Please refer to the official docs on connecting to a MySQL DB in Google Cloud. Let me know if you have any additional concerns or questions.
