### ISSUE TITLE
feat: want handy method 

### ISSUE THREAD

**Issue by shivashankar16041990** [VeryGoodOpenSource/dart_frog#543]
**Description**
suppose as in counter example it is difficult to remember 
`handler.use(provider<int> ((handler) =>++_count));`

so come up with handy method please see below two file , i have added the handy method there and it works fine
[ i hope you understand]

middleware is like this

```
import 'package:dart_frog/dart_frog.dart';
 int _count=0;
 Handler middleware(Handler handler){
                      return handlerWith<int>(value:++_count, handler: handler);

}


//handy method
Handler handlerWith<T extends Object>({required T value,required Handler handler}){
   return handler.use(provider<T> ((handler) =>value));

 }
```
below is index.dart file
```
import 'package:dart_frog/dart_frog.dart';

Response onRequest(RequestContext context) {
  final count=context.read<int>();
  return Response(body: ' you have accessed this page $count times');
}

```

**Requirements**

- [ ] Checklist of requirements to be fulfilled

**Additional Context**

**Comment by felangel** [comment]
> **Description** suppose as in counter example it is difficult to remember `handler.use(provider<int> ((handler) =>++_count));`
> 
> so come up with handy method please see below two file , i have added the handy method there and it works fine [ i hope you understand]
> 
> middleware is like this
> 
> ```
> import 'package:dart_frog/dart_frog.dart';
>  int _count=0;
>  Handler middleware(Handler handler){
>                       return handlerWith<int>(value:++_count, handler: handler);
> 
> }
> 
> 
> //handy method
> Handler handlerWith<T extends Object>({required T value,required Handler handler}){
>    return handler.use(provider<T> ((handler) =>value));
> 
>  }
> ```
> 
> below is index.dart file
> 
> ```
> import 'package:dart_frog/dart_frog.dart';
> 
> Response onRequest(RequestContext context) {
>   final count=context.read<int>();
>   return Response(body: ' you have accessed this page $count times');
> }
> ```
> 
> **Requirements**
> 
> * [ ]  Checklist of requirements to be fulfilled
> 
> **Additional Context**

Hi @shivashankar16041990 👋
Thanks for opening an issue!

There is a subtle difference which is that the helper method you've created doesn't provide developers with the current RequestContext in their create callback so it makes it impossible to provide a value that depends on another provided value like:

```dart
handler.use(
  provider<String>((context) {
    final value = context.read<int>();
    return value.toString();
  });
```

In addition, I would prefer not to include syntactic sugar into the library at this stage especially given you can already achieve what you are asking for without any changes to Dart Frog. In addition, we have plans to support reusable snippets in the future which will hopefully make having to remember the syntax less of an issue. Let me know what you think and thanks again!

**Comment by shivashankar16041990** [comment]
ok

**Comment by felangel** [comment]
Closing for now but feel free to comment with any follow ups and I’m happy to continue the conversation 👍
