### ISSUE TITLE
feat: add UDP socket

### ISSUE THREAD

**Issue by hamidjalili59** [VeryGoodOpenSource/dart_frog#555]
**Description**

For greater flexibility, we need to manually determine the type of communication (TCP/UDP) in the Web-Socket protocol. For example, to improve communication in game servers or voice chats, UDP should be used.

**Requirements**

- User-defined communication protocol determination.

**Comment by wolfenrain** [comment]
Hi thank you for opening an issue! Can you maybe specify a bit more on what exactly you mean? 

Websockets are using TCP as it is made on top of the HTTP protocol so there is no different type of communication the Websocket protocol.

**Comment by hamidjalili59** [comment]
For voice chat communication, the UDP protocol is better. The reason is that voice chat requires continuous and high-volume data that needs to be transferred quickly, and any slight delay in data transfer can result in a decrease in audio quality. The UDP protocol is designed for the transmission of unguaranteed and continuous data and transfers data without the need to ensure their arrival. Therefore, UDP is a suitable option for voice chat communication, which requires high-speed and high-quality transmission. On the other hand, TCP protocol is the best option for transferring data that needs to be guaranteed, such as large files and sensitive information.

**Comment by Ayush-Suman** [comment]
Websocket is an application layer protocol that by definition uses TCP as its transport layer You might be interested to look into WebRTC.

**Comment by hamidjalili59** [comment]
thank you for answer
