### ISSUE TITLE
fix: dart_frog update not working

### ISSUE THREAD

**Issue by dhrubrawat66** [VeryGoodOpenSource/dart_frog#565]
dart_frog upate not working.

**Screen
![Screenshot 2023-03-11 232251](https://user-images.githubusercontent.com/85351405/224503410-14698de7-e0a8-4d48-a3b5-1842a80a334e.png)
shots**

**Comment by rubenferreira97** [comment]
I think this is not a bug. `dart_frog` and `dart_frog_cli` are different packages. Normally you install `dart_frog_cli` as a global package. So when you run `dart_frog update` you are updating `dart_frog_cli` (dart global package). Currently, `dart_frog_cli` latest version is `0.3.3`.
