### ISSUE TITLE
fix: Dockerfile is not inherited during build production

### ISSUE THREAD

**Issue by serezhia** [VeryGoodOpenSource/dart_frog#569]
**Description**

If you add a Dockerfile to the project folder and change it, a clean Dockerfile will be generated in the build folder

**Steps To Reproduce**

1. Create new dart_frog project (dart_frog create test)
2. Create new Dockerfile in root folder 
3. Edit Dockerfile in root folder 
4. Create production build (dart_frog build)

**Expected Behavior**

I expected that Dockerfile would be copied from the root folder , and not create a new Dockerfile

**Comment by mafreud** [comment]
Same issue.
