### ISSUE TITLE
feat: Will dart_frog support graphql?

### ISSUE THREAD

**Issue by hwangblood** [VeryGoodOpenSource/dart_frog#576]

**Comment by wolfenrain** [comment]
Hi, Dart Frog wont support GraphQL out of the box itself but any GraphQL implementation that is made for Shelf should work with Dart Frog as it uses Shelf internally.

But if we look at it from the context of Dart Frog it wont be supported. If you have any other questions, feel free to open another issue!

**Comment by ecoant** [comment]
> any GraphQL implementation that is made for Shelf should work

are there any projects you know of and can recommend?
