### ISSUE TITLE
docs: update `CONTRIBUTING.md`

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/dart_frog#577]
**Description**

As a developer interested in contributing I would like to have a `CONTRIBUTING.md` file that outlines:
1. How to run the tool in my local environment
2. How the overall structure of the tool works (explained with visualisations)
3. Know on what features the team would like external contributors to work and how to create a correct pull request.

**Requirements**

- [ ] Explain how the tool works internally (with visualisations)
- [ ] Include instructions on how to run the tool in my local environment (for MacOs, Windows and Linux)
- [ ] Include instructions on how to find features available for contribution or suggest features
- [ ] Include instructions on how to open a good pull request or issue

**Comment by easazade** [comment]
and how do you manage the mono-repo? 
usually i see melos package is used for that. do you create a workspace in your IDE or is there any other tools you guys use internally in tour team?

**Comment by alestiago** [comment]
Linking this related comment here https://github.com/VeryGoodOpenSource/dart_frog/issues/631#issuecomment-1546227999
