### ISSUE TITLE
feat: Allow to map a `throw` to a custom `Response`

### ISSUE THREAD

**Issue by rubenferreira97** [VeryGoodOpenSource/dart_frog#578]
There are some cases where I find myself the need to "panic"/stop the onRequest execution and send an early response to the client (normally deep down on the call stack).
An usecase for this is `context.request.json()`. This function responds with 500 (Internal Server Error) if we pass a empty string (request body).
In every `onRequest` I have to write the following code to send a 400 (Bad Request):
```dart
//onRequest
try {
  final json = await context.request.json();
  // my code nested :(
} on FormatException {
  return Response(statusCode: HttpStatus.badRequest);
}
```

Would be plausible to throw something like a custom `ResponseException`? It would work like the following:
```dart
Future<dynamic> json() async {
  try {
    await jsonDecode(await body());
  }  on FormatException {
    throw ResponseException(Response(statusCode: HttpStatus.badRequest));
  }
}

// top level
try {
  response = await handler(shelfRequest);
} on ResponseException catch (error, stackTrace) {
  // send Response present in ResponseException
  response = error.response;
} catch (error, stackTrace) {
  // 500 internal error
}
```

I would guess `request.formData()` suffers from the same problem (responds with 500).

TBH I don't 100% like this approach since it breaks control flow with exceptions, but I can't think of a better way without modifying the current approach.

**Comment by rubenferreira97** [comment]
After giving some thought another approach that I find more reasonable and composable is the ability to register an exception mapper on top-level or even at middleware level like:
```dart
// middleware level
Handler middleware(Handler handler) {
  return handler.use(
    exceptionMapper((mapper) => mapper
      ..map<FormatException>(Response(statusCode: 400))
      ..map<IntegerDivisionByZeroException>(Response(statusCode: 500, body: Can't divide by 0.'))
  );
}

// or

Handler middleware(Handler handler) {
  return handler.use(
    exceptionMapper((throwable) =>
      switch (throwable) {
        FormatException() => Response(statusCode: 400),
        IntegerDivisionByZeroException() => Response(statusCode: 500, body: Can't divide by 0.'),
      }
    )
  );
}
```

**Comment by GabrielRozendo** [comment]
I needed something like that (and more things) 
What I did with some comments and it really solved my problems.

Create a "Main middleware" and use it in `use` on `serve`

and create some custom exceptions (one class `AppException` with status code, error message, etc)
my "main middleware" is something like that:

```dart
Middleware mainMiddleware() {
  return (innerHandler) {
    return (context) async {
      final watch = Stopwatch()..start();

      try {
       
        logger.log( ... ); // I've create my own logger handler

       // { ... }

        final response = await innerHandler
            //.use(...) // any more middleware I need, like DataBase
(context);

        if (response.statusCode == 404) {
          throw AppException.notFound('Endpoint not found');
        }

        logger.logRequest(LogHttpMessage( /* my log obj */ ));

        return response;
      } catch (e, s) {
// It could be my specific catch too
// } on AppException catch(e) {
        final AppException error;

        if (e is AppException) { // if is my own exception, it is already handled, so it is my "error".
          error = e;
        } else { 
// otherwise I create an "internal error"
// not handled and answer in API with a default error response
// and the stack trace to log it and check it out later
          error = AppException.internalError(
            e.toString(),
            stackTrace: s,
          );
        }

        logger.logErrorRequest(
          //LogHttpError(...          ),
        );

// My AppException has a specific statusCode to return from API
// and a specific error message to return from Response
        return Response.json(
          statusCode: error.statusCode,
          body: error.toJson(),
        );
 ....
```

**Comment by erickzanardo** [comment]
This problem could be approached in many different ways, and in many instances, it can depend on how the user wants that to be handled.

Given that this can be easily implemented by the developer using a middleware, and how hard it would be to come up with a generic solution that would work for all the different cases, we don't plan on adding a generic error response handling, but rather suggest the developers to rely on middleware in order to do so.

Regardless of that, thanks so much for opening this suggestion and feel free to open other that you might think of 💙
