### ISSUE TITLE
fix: Dependencies that depend on other dependencies

### ISSUE THREAD

**Issue by HoussemBousmaha** [VeryGoodOpenSource/dart_frog#607]
Hi! i want to get an object in the onRequest method, but this object depends on another object that i do not want to expose to the onRequest method.

for instance:

![image](https://user-images.githubusercontent.com/86262467/232260121-9972b70d-5210-4bfc-90cb-a8b054ec23e0.png)

![image](https://user-images.githubusercontent.com/86262467/232260129-976953fe-41a9-4976-9011-65f4b2af4862.png)

![image](https://user-images.githubusercontent.com/86262467/232260132-67ac9b1f-7218-497c-9ee2-37f30eafecc6.png)

![image](https://user-images.githubusercontent.com/86262467/232260135-051b858e-400c-44d4-90c8-87b5b8870a1c.png)

i want to implement this behavior i get some weird error

Error thrown by handler.
Bad state: context.read<IJWTService>() called with a request context that does not contain a IJWTService.

This can happen if IJWTService was not provided to the request context:
  ```dart
  // _middleware.dart
  Handler middleware(Handler handler) {
    return handler.use(provider<T>((context) => IJWTService());
  }


any solutions?

**Comment by felangel** [comment]
@HoussemBousmaha can you share a link to a minimal reproduction sample? I’m guessing the order of your providers is backwards but it would be much easier to help if you could provide a link to a minimal reproduction sample, thanks!

**Comment by HoussemBousmaha** [comment]
Yes! i reversed the order and it worked!

![image](https://user-images.githubusercontent.com/86262467/232266762-e7c8db22-3098-4d26-9cf2-874864f5a0cd.png)

thank you!
