### ISSUE TITLE
fix: dynamic routes override non dynamic ones.

### ISSUE THREAD

**Issue by erickzanardo** [VeryGoodOpenSource/dart_frog#658]
**Description**

When declaring a dynamic route, they will always take precedence over a non dynamic on. For example, imagine that I have the following route:

`GET /turtles/[id]`

And the following:

`POST /turtles/random`

When calling `curl -X POST http://localhost:8080/turtles/random`, `routes/turtles/[id]/index.dart` will be called instead of `routes/turtles/random.dart`, which can be confusing.

**Steps To Reproduce**

1. clone https://github.com/erickzanardo/ninja_turtles_api
2. start the server
3. `curl -X POST http://localhost:8080/turtles/random`
4. See the 405 error

**Expected Behavior**

I understand that this can be considered an expected behaviour, one could argue that `random` is simply an `id` that the `index.dart` inside the /turtles/[id]/` folder should consider and handle. Which I completely agree, but on the other hand, `random.dart` and `[id]/index.dart` files are conflicting routes.

I believe there are two possible ways of fixing this:
 - Non dynamic routes should take precedence over dynamic ones, so we could check for non dynamic route handlers before checking in dynamics ones, that way the example above would work. I believe this to be a preferred way of handling this, being able to split handlers like this can lead to a more organized route structure where we would be able to better split similar routes in different files.
 - Identify these conflicts and give a warning to the user

**Comment by alestiago** [comment]
Linking a similar issue #631 for reference.
