### ISSUE TITLE
provider doesn't support nullable values

### ISSUE THREAD

**Issue by bohdan1krokhmaliuk** [VeryGoodOpenSource/dart_frog#688]
**Description**

I am not sure that it is a bug, as I couldn't find any community to ask it - leaving it here.
Why provider can't provide nullable values, is there any specific reason for it? 
It may be useful in some cases to have this feature.

Original code:
```  
RequestContext provide<T extends Object>(T Function() create) {
    return RequestContext._(
      request._request.change(
        context: {...request._request.context, '$T': create},
      ),
    );
  }
```

From this code I can say that '$T' on nullable value will also return string aka "MyType?" - so unfortunatelly I don't see any visible reason not to fix it

**Comment by felangel** [comment]
A use case would be if you're using context to provide a `UserIdentity` object which is determined from a jwt. You would likely want to provide a nullable `UserIdentity` to determine whether or not the request is associated with a `UserIdentity`.
