### ISSUE TITLE
feat(dart_frog_cli): include `uninstall` command to uninstall `dart_frog_cli`

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/dart_frog#709]
**Description**

As a user I would like to uninstall `dart_frog_cli` by using `dart_frog uninstall`, this should:

- Remove global files created when installing `dart_frog_cli` (for example, completion files)
- Deactivate `dart_frog_cli`

**Additional Context**

- Useful for sharing uninstallation logic between IDE extensions.
- Improve user's experience since currently a full uninstall requires:
```sh
dart_frog uninstall-completion-files # Hidden command most users are not aware of.
dart pub global deactivate dart_frog_cli
```

**Comment by renancaraujo** [comment]
Logging some of the decisions we made about this:

We should not assume that the CLI was installed via pub global activation, even though as of today, this is the only official way to install the DF CLI. As a result, there is not precise way to programmatically uninstall the CLI.

To tackle this issue now, one must: 
-  Add an uninstall section to the DF docs site
- Add the uninstall command to the CLI that will print a link to that section.

**Comment by jsgalarraga** [comment]
I can tackle this one 😄
