### ISSUE TITLE
fix(dart_frog_cli): changelog link is "not found"

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/dart_frog#724]
**Description**

When an update is available the "Changelog" link leads to a 404. 

See image, that shows the link https://github.com/verygoodopensource/dart_frog/releases/tag/dart_frog_cli-v0.3.8.

![Screenshot 2023-06-25 at 19 07 30](https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/9ed74f23-76b5-4dd0-a08c-27be662917ee)

**Comment by wolfenrain** [comment]
This happened because we tagged the CLI on the wrong tag, this was fixed last week by @renancaraujo

Closing as fixed.
