### ISSUE TITLE
fix(dart_frog_cli): creating new route or middleware doesn't have single EOL

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/dart_frog#746]
**Description**

Creating a new route or middleware generates a file that has _eol_at_end_of_file_ formatting errors (when using Very Good Analysis).

**Steps To Reproduce**

1. Create a Dart Frog project (from anywhere sensible)
```sh
dart_frog create sample
```

2. Analyze the project (from /sample)
```sh
dart analyze 
```
The above has no issues, as expected.

3. Create a new route (from /sample)
```sh
dart_frog new create hello
```

4. Analyze the project once again (from /sample)
```sh
dart analyze
```
The above throws an `eol_at_end_of_file` error for `routes/hello.dart`, not expected.

5. Create a new middleware (from /sample)
```sh
dart_frog new middleware world
```
The above throws an `eol_at_end_of_file` error for `routes/world/_middleware.dart`, not expected.

**Expected Behavior**

- Generated routes or middleware file should not have a `eol_at_end_of_file` error upon creation.

**Screenshots**

![CleanShot 2023-07-11 at 09 30 21](https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/ccefdbff-f335-444c-9b6d-23178875fbd4)

**Additional Context**
- [`eol_at_end_of_file` rule ](https://dart.dev/tools/linter-rules/eol_at_end_of_file)

**Comment by jsgalarraga** [comment]
👋🏼
