### ISSUE TITLE
feat: IntelliJ extension support

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/dart_frog#775]
**Description**

As mentioned on the roadmap, this issue is requesting to provide support for IntelliJ. 

There is currently an issue tracking both VS Code and IntelliJ, see https://github.com/VeryGoodOpenSource/dart_frog/issues/286. On the other hand, this issue only requests for IntelliJ support and will be used to track the progress instead.

**Requirements**

- [ ] An IntelliJ extension that allows creating a project
- [ ] An IntelliJ extension that allows creating new routes
- [ ] An IntelliJ extension that allows creating new middleware
- [ ] An IntelliJ extension that allows attaching a debugger

**Comment by tomarra** [comment]
We don't currently plan on creating an IntelliJ extension as our typical workflow is focused on VS Code at this time. If someone from the community would like to create a PR to address it we can provide feedback and guidance for getting it merged in but it's not on our short term roadmap.

**Comment by kaljitism** [comment]
@tomarra @alestiago I want to create a PR and create the extension for IntelliJ, Can you guide me regarding this?
