### ISSUE TITLE
fix: build server

### ISSUE THREAD

**Issue by hitchhicker007** [VeryGoodOpenSource/dart_frog#78]
**Build server does not start after executing `dart build/bin/server.dart` command**

**Comment by hitchhicker007** [comment]
1. dart_frog version: 0.0.2-dev.3
2. My OS: Ubuntu 22.04 LTS
3. `dart_frog dev` is working properly
4. there's no dart process working in the background

**Comment by felangel** [comment]
> 1. dart_frog version: 0.0.2-dev.3
> 2. My OS: Ubuntu 22.04 LTS
> 3. `dart_frog dev` is working properly
> 4. there's no dart process working in the background

Thanks! Can you describe what happens? It would be awesome if you could share a screen recording 👍

**Comment by hitchhicker007** [comment]
Here's the screencast of the problem.
[Screen Recording](https://drive.google.com/file/d/12eCDAP6Esl34eGfo2kHw7aaf13EQ3NoB/view?usp=sharing)

**Comment by felangel** [comment]
> Here's the screencast of the problem.
> [Screen Recording](https://drive.google.com/file/d/12eCDAP6Esl34eGfo2kHw7aaf13EQ3NoB/view?usp=sharing)

Thanks for sharing! That looks normal. Are you sure the server wasn’t running? Did you try making a request to one of your endpoints?

**Comment by hitchhicker007** [comment]
Yes, you are right. The problem is that it does not show any message in the CLI.

**Comment by felangel** [comment]
That is working as expected. Sorry for the confusion/inconvenience we can add a log to indicate it’s running in production mode 👍
