### ISSUE TITLE
feat: simpler support for freezed

### ISSUE THREAD

**Issue by dbilgin** [VeryGoodOpenSource/dart_frog#80]
**Description**

I believe a lot of people in the dart community are using pubs like [freezed](https://pub.dev/packages/freezed). When I was recently trying to use it, I realised I can't just have a models folder in the root and use freezed like that, I had to put the dart files that would be generated under the `lib` directory.
I feel like this kind of makes it lose the point of dart_frog not using the libs folder.
Perhaps I missed something here?

Same thing would be happening with `dart doc .`. Although I am aware that's not really needed if there is eventually swagger support.

**Requirements**

- [ ] A way to use freezed naturally with dart_frog

**Comment by felangel** [comment]
Hi @dbilgin 👋 
Thanks for opening an issue!

At this stage, the intention was for all code that is not related to routing to live in the `lib` folder just like a traditional dart application. In this case, as you mentioned, your freezed models could like under `lib/src`.

> I feel like this kind of makes it lose the point of dart_frog not using the libs folder.

Can you elaborate a bit on this? Are you suggesting that `dart_frog` should require that `routes` be defined in the `lib` folder as well? Thanks!

**Comment by dbilgin** [comment]
Oh no, not at all, I was actually not aware that the intention was to keep the code that's unrelated to routing inside `lib`, that actually clears it up for me quite well. Thank you very much @felangel!
