### ISSUE TITLE
fix: dev server does not release ports on linux after kill

### ISSUE THREAD

**Issue by renancaraujo** [VeryGoodOpenSource/dart_frog#807]
**Description**

After starting a dev server, killing the underlying dart process doesn't kill the server process.  As indicated by this e2e workflow run:

https://github.com/VeryGoodOpenSource/dart_frog/actions/runs/5670059745/job/15364840497

<img width="1089" alt="Screenshot 2023-07-26 at 12 01 16" src="https://github.com/VeryGoodOpenSource/dart_frog/assets/6718144/cf2257a6-6f40-4a3b-ab40-b778968c3f08">

**Steps To Reproduce**

1. run `dart_frog dev` on a Linux machine
2. kill the command line with `ctrl+c`
3. There is still a local server running on :8080

**Expected Behavior**

The local server should be killed alongside the CLI.

**Additional Context**

This also happens if the dev server is started via the daemon.

**Comment by wolfenrain** [comment]
Was no longer able to reproduce and the E2E seems to work correctly as well, closing this.

If you see this problem happening again please open up a new issue with a reproduce-able example <3
