### ISSUE TITLE
docs(vscode): How to run on VSCode

### ISSUE THREAD

**Issue by JCKodel** [VeryGoodOpenSource/dart_frog#877]
**Description**

There is no documentation nor results on Google in how to create a `launch.json` in VSCode to debug Dart Frog projects.

What I did was to run `dart_frog dev` once, then it creates a `.dart_frog/server.dart`, then I could use that as an entry-point to a normal Dart project (and breakpoints hits normally).

The problem is: there should be a task or something that generates that `server.dart` before hand.

The goal is to press [F5] and start debugging a Dart Frog project with hot reload.

**Comment by alestiago** [comment]
Hi @JCKodel thanks for opening an issue!

We're currently working on attaching smoothly to the debugger by using the new daemon, so you can expect this to be as easy "as pressing [F5] and start debugging a Dart Frog project with hot reload". It will soon be available.

In the meantime, we had a Pull Request with the documentation you are requesting, you can read more about it here: https://github.com/VeryGoodOpenSource/dart_frog/pull/573.

I hope this helps, let me know your thoughts!

**Comment by JCKodel** [comment]
Thank you for getting back to me.

Actually, I went a different path... since I was needing to actually validate if some requests are indeed GET, instead of doing it on the handler, I took ownership of the generated Dart Frog code instead, so I could change `Router()..get("/route")` instead of `.all`.

Then, this way, is just a matter of running a common Dart program, setting `program` to `${workspaceFolder}/main.dart`

Guess this should figure out in docs Advanced section.

**Comment by alestiago** [comment]
@JCKodel I'll be closing this issue since the next version of the VS Code extension will allow to easily run and debug Dart Frog projects. If you're interested in the progress check, https://github.com/VeryGoodOpenSource/dart_frog/pull/955 and https://github.com/VeryGoodOpenSource/dart_frog/issues/957.

Feel free to re-open if there is something we're missing. Thanks again for opening the issue 💙 !
