### ISSUE TITLE
feat: we can use prisma orm with dart frog ? 

### ISSUE THREAD

**Issue by rectrick** [VeryGoodOpenSource/dart_frog#892]
we can use prisma orm with dart frog ?

**Comment by alestiago** [comment]
Somewhat related to the discussion over https://github.com/VeryGoodOpenSource/dart_frog/issues/316.

**Comment by alestiago** [comment]
Hi @rectrick , I've looked into Prisma. Theoretically you should be able to use Prisma and Dart Frog together, however Prisma "has sadly suspend maintenance of the project" and therefore it is unlikely we will invest time into a detailed tutorial that explains step by step how to integrate both of them together. For now, I can simply recommend looking at the [Prisma documentation ](https://prisma.pub/docs/getting-started.html) and the [Dart Frog documentation](https://dartfrog.vgv.dev/docs/overview) to learn how to do so.

I'll be closing this issue, if you would have any further questions feel free to re-open! Thank you 🙌
