### ISSUE TITLE
fix: remove one topic in `dart_frog_auth`

### ISSUE THREAD

**Issue by jxstxn1** [VeryGoodOpenSource/dart_frog#906]
**Description**

According to https://dart.dev/tools/pub/pubspec#topics, only 5 topics are allowed.
`dart_frog_auth` is using 6 topics currently. 
This will run into checks from `pub.dev` as soon as you run `dart pub lish`.

**Comment by erickzanardo** [comment]
Hey @jxstxn1 thanks so much for opening the issue and offering to submit a PR, But we ended up addressing that in the past release.
