### ISSUE TITLE
chore: add .DS_Store File to generated .gitignore

### ISSUE THREAD

**Issue by jxstxn1** [VeryGoodOpenSource/dart_frog#909]
**Description**

As a MacOS User, it would help to get the `.DS_Store` File ignored by default in a new dart_frog project.

**Requirements**

- [ ] Add `.DS_Store` to gitignore

**Comment by alestiago** [comment]
@jxstxn1 would you like to be assigned to this issue?

**Comment by jxstxn1** [comment]
Yeah, for sure :)
