### ISSUE TITLE
fix(dart_frog_cli): daemon should report when there is missing params 

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/dart_frog#913]
**Description**

Running the daemon and sending a request with a missing parameters field returns an error with a message that could be more descriptive.

**Steps To Reproduce**

1. Create a Dart Frog project:

```sh
dart_frog create sample
```

2. Start the daemon on the project (from /sample):
```sh
dart_frog daemon
```

3. Send an invalid message without params (within the deamon session):
```
[{"id":"1","method":"dev_server.start"}]
```

4. The error message is:
```
[{"id":"1","error":{"message":"Malformed message, invalid workingDirectory"}}]
```

**Expected Behavior**

To report that the request is missing a prams field with the required parameters instead of reporting an invalid workingDirectory.

**Screenshots**

Reproductive steps output from terminal:
![CleanShot 2023-08-09 at 08 57 26](https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/f4a0d241-62ec-4542-a4a9-8a7517a1b5b5)

**Additional Context**

 - https://github.com/VeryGoodOpenSource/dart_frog/blob/88a65d939964b0c2786e771850ce4a3cfc637871/packages/dart_frog_cli/lib/src/daemon/domain/dev_server_domain.dart#L42

**Comment by Yczar** [comment]
Hopping on this 🥂

**Comment by alestiago** [comment]
@Yczar are you still on this?

**Comment by alestiago** [comment]
Thanks @Yczar for hopping into this, due to a two week inactivity I'll clear assignees. Let me know if you would like to take the lead here again, and I'll reassign you. If anyone else is interested in taking this on, let us know.

**Comment by alestiago** [comment]
@PiotrFLEURY

**Comment by renancaraujo** [comment]
I had an idea. What if we centralize the parameter recovery within a method?

```dart
final paramValue = request.getParam<String>('requiredValue');
final paramValue = request.getParam<String?>('optionalValue');
```

**Comment by PiotrFLEURY** [comment]
Hi everyone !

@alestiago  I just proposed the #1050 pull request to fix this issue.

Thanks @renancaraujo for the syntax suggestion.

Feel free to challenge my code.
