### ISSUE TITLE
feat: Authentication using tokenization

### ISSUE THREAD

**Issue by mhmzdev** [VeryGoodOpenSource/dart_frog#914]
**Description**

I'm trying to add authentication in an open source project which is developed using dart_frog and flutter. But I'm unable to find a proper way of using JWT token for this purpose.
I've tried to find a way online but failed, if there's any example I would love to take a look at that.

Link: https://github.com/mhmzdev/full-stack-flutter-app

**Requirements**

- [x] dart_frog auth documentation
- [x] other dart packages that will be used along side for JWT

**Comment by erickzanardo** [comment]
We have just recently released a tutorial that covers that: https://dartfrog.vgv.dev/docs/tutorials/jwt_authentication

Let us know if there is anything else missing that we should cover.

Thanks!
