### ISSUE TITLE
fix: Breakpoints not working in Version 1.0.0

### ISSUE THREAD

**Issue by Wizzel1** [VeryGoodOpenSource/dart_frog#937]
**Description**

I am trying to debug my server with breakpoints but I can't get them to work. Does this have something to do with dart_frog or is there something I can do on my side to fix it?

**Comment by alestiago** [comment]
Hi @Wizzel1 ! Thanks for opening an issue. I am able to debug projects using dart_frog 1.0.0. How are you attaching to the debugger?

**Comment by Wizzel1** [comment]
@alestiago I just set the breakpoints. I think it worked when I tried dart_frog 6 months ago so I was assuming I did not need anything else. Is that wrong?

**Comment by alestiago** [comment]
Hi @Wizzel1, there are many ways one can attach to the debugger. For the time being, I would recommend doing:

1. Start the development server (from project root):
```sh
dart_frog dev
```

2. Copy the VM service address given upon start:
```sh
The Dart VM service is listening on http://127.0.0.1:8181/UriyM0Wnj2E=/
```
You should copy "http://127.0.0.1:8181/UriyM0Wnj2E=/"

3. Open the command palette (usually binded to the shortcut Command + Shift + P) and look for "Debug: Attach to Dart Process".

4. Past the VM service URI in the prompt.

5. Start debugging 🐛

<details>

<summary> Video demonstration </summary>

https://github.com/VeryGoodOpenSource/dart_frog/assets/44524995/76b92ce5-de1a-4674-8da6-1956a1b202c1

</details>

---

**Note:**  I'm assuming you are using VS Code as your IDE and that you already have the Dart extension installed. I'm not an Android Studio user but I believe a similar process can be done with the Dart extension for Android Studio.

We are currently working on simplifying and improving this process in the [Dart Frog VS Code extension](https://marketplace.visualstudio.com/items?itemName=VeryGoodVentures.dart-frog).

Please let me know if this resolves your issue 🙌

**Comment by Wizzel1** [comment]
@alestiago Yes, that worked. I could have sworn that I didn't do that the last time I used dart_frog. Thanks for the quick help!
