### ISSUE TITLE
feat: web socket support

### ISSUE THREAD

**Issue by CodeDoctorDE** [VeryGoodOpenSource/dart_frog#94]
**Description**

Hello,
first of all: Thank you for this package. After aqueduct was closed, there was no real alternative to create the server in the same language as the flutter application.
Currently I want to built a real time chat application. For this, I need to support web sockets to communicate with the client.
https://pub.dev/packages/shelf_web_socket is a shelf socket plugin that can be used for this.

**Requirements**

- [x] Checklist of requirements to be fulfilled

**Additional Context**

\-

**Comment by ushieru** [comment]
You can add web sockets with [shelf_web_socket](https://pub.dev/packages/shelf_web_socket) package. Dart frog have a fromShelfHandler wrapper.

ws example:
```dart
// routes/ws.dart

import 'dart:async';

import 'package:dart_frog/dart_frog.dart';
import 'package:shelf_web_socket/shelf_web_socket.dart' as ws;

FutureOr<Response> onRequest(RequestContext context) async {
  return fromShelfHandler(
    ws.webSocketHandler((webSocket) {
      webSocket.sink.add('Hello from Dart Frog - Web Socket 🐸');
    }),
  )(context);
}

```

index.html example:
```html
<!-- public/index.html -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        let socket = new WebSocket("ws://localhost:8080/ws");
        socket.onmessage = function (event) {
            console.log(event)
        };
    </script>
</body>

</html>
```

<details>
<summary style="font-size:14px">Result</summary>
<img alt="console image" src="https://user-images.githubusercontent.com/32021976/189743127-463ba40c-2a25-4ff8-a162-522e2ac99fb9.png" />
</details>

**Comment by ushieru** [comment]
If possible i would like to add this feature. :D
