### ISSUE TITLE
Fix: Wrong warning about Route conflict after hot reload

### ISSUE THREAD

**Issue by KarelSima** [VeryGoodOpenSource/dart_frog#963]
**Description**

On version 1.0.0,
after hot reload of server with mix static and dynamic routes, dev server generates false route conflict detected.

**Steps to reproduce**.

Create files in same subfolder : 
[id].dart
add.dart 
all.dart

And after each next hot reload you will see Route Conflict Detect.
The function of these endpoints ([id] add and all) works well, the problem seems to be only the output of false warnings.

***Example :***
`Route conflict detected. \v1\type\<id> and \v1\type\all both resolve to /v1/type/<id>.`
`Route conflict detected. \v1\type\<id> and \v1\type\add both resolve to /v1/type/<id>.`

**Comment by tomarra** [comment]
Closing this out as a won't fix. As noted in the comment above, this is expected behavior.
