### ISSUE TITLE
fix: pub.dev page missing parts that in readme

### ISSUE THREAD

**Issue by guyluz11** [VeryGoodOpenSource/dart_frog#976]
Both the `Documentation` section and `Packages` exist in the readme but missing from pub.dev.
I would argue that the `Documentation` part is very important to understand what is the package about.

In readme
![image](https://github.com/VeryGoodOpenSource/dart_frog/assets/9304740/b18abd64-9262-4412-a3a7-c0c8e63e96f7)

In pub.dev
![image](https://github.com/VeryGoodOpenSource/dart_frog/assets/9304740/04c4a088-3b91-4e19-8eaf-a0d172fcd5b2)

Is that just old version?

**Comment by renancaraujo** [comment]
Hello there!

This repository is a monorepo, which means that the front-facing README is not the same as package README.  The one you see on pub.dev is under `packages/dart_frog`.


Now that is clear why they are different, I agree that the package README should include the docs section, but I am no sure about the package table (which serves as a repository summary).

**Comment by renancaraujo** [comment]
Created #978 adding links to docs on all of our package readmes. Thanks for pointing this out.
